.\"
.\" Man page for OMPI's ompi-ps command
.\" 
.\" .TH name     section center-footer   left-footer  center-header
.TH     OMPI-PS  1       "June 2006" "Open MPI"   "OPEN MPI COMMANDS"
.\" **************************
.\"    Name Section
.\" **************************
.SH NAME
.
ompi-ps, orte-ps \- Displays information about the active jobs and processes 
in Open MPI.
.
.PP
.
\fBNOTE:\fP \fIompi-ps\fP, and \fIorte-ps\fP are exact
synonyms for each other. Using any of the names will result in exactly
identical behavior.
.
.\" **************************
.\"    Synopsis Section
.\" **************************
.SH SYNOPSIS
.
.B ompi-ps
.R [ options ]
.
.\" **************************
.\"    Options Section
.\" **************************
.SH Options
.
To be written...
.
.
.\" **************************
.\"    Description Section
.\" **************************
.SH DESCRIPTION
.
.PP
\fIompi-ps\fR ...
.
.
.\" **************************
.\"    See Also Section
.\" **************************
.
.SH SEE ALSO
orterun(1)
.
