.TH MPI_File_c2f 3 "11/3/1998" " " "MPI-2"
.SH NAME
MPI_File_c2f \-  Translates a C file handle to a Fortran file handle 
.SH SYNOPSIS
.nf
#include "mpi.h"
MPI_Fint MPI_File_c2f(MPI_File fh)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- C file handle (handle)
.PD 1

.SH RETURN VALUE
Fortran file handle (integer)
