.TH MPI_File_iread_shared 3 "9/3/1998" " " "MPI-2"
.SH NAME
MPI_File_iread_shared \-  Nonblocking read using shared file pointer 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPI_File_iread_shared(MPI_File fh, void *buf, int count, 
                          MPI_Datatype datatype, MPIO_Request *request)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B fh 
- file handle (handle)
.PD 1
.PD 0
.TP
.B count 
- number of elements in buffer (nonnegative integer)
.PD 1
.PD 0
.TP
.B datatype 
- datatype of each buffer element (handle)
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B buf 
- initial address of buffer (choice)
.PD 1
.PD 0
.TP
.B request 
- request object (handle)
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 'MPI_WTIME' and 'MPI_WTICK')
have an additional argument 'ierr' at the end of the argument list.
'ierr' is an integer and has the same meaning as the return value of
the routine in C.  In Fortran, MPI routines are subroutines and are
invoked with the 'call' statement.

All MPI objects (e.g., 'MPI_Datatype', 'MPI_Comm', 'MPI_File') are of
type 'INTEGER' in Fortran.
