.TH MPIO_Test 3 "2/5/1998" " " "MPI-2"
.SH NAME
MPIO_Test \-  Test the completion of a nonblocking read or write 
.SH SYNOPSIS
.nf
#include "mpi.h"
int MPIO_Test(MPIO_Request *request, int *flag, MPI_Status *status)
.fi
.SH INPUT PARAMETERS
.PD 0
.TP
.B request 
- request object (handle)
.PD 1

.SH OUTPUT PARAMETERS
.PD 0
.TP
.B flag 
- true if operation completed (logical)
.PD 1
.PD 0
.TP
.B status 
- status object (Status)
.PD 1

.SH NOTES FOR FORTRAN
All MPI routines in Fortran (except for 'MPI_WTIME' and 'MPI_WTICK')
have an additional argument 'ierr' at the end of the argument list.
'ierr' is an integer and has the same meaning as the return value of
the routine in C.  In Fortran, MPI routines are subroutines and are
invoked with the 'call' statement.

All MPI objects (e.g., 'MPI_Datatype', 'MPI_Comm', 'MPI_File') are of
type 'INTEGER' in Fortran.
