# MPI C++ Compiler command, Compiler Flags, and MPI Library
MPICXX = vtcxx -vt:cxx mpicxx
MPICXXFLAGS = -g
MPILIB =

# Example targets:
# <prog>-man   == manual: functions and loops by using VampirTrace's API
# <prog>-comp  == automatic: functions by using compiler
# <prog>-dyn   == binary-automatic: functions by using Dyninst
# (comment line to disable a target)

# HELLO (Hello World (MPI))
HELLO_TGT1 = hello-man
HELLO_TGT2 = hello-comp
#HELLO_TGT3 = hello-dyn

# PI (Approximates the value of pi (MPI))
PI_TGT1    = pi-man
PI_TGT2    = pi-comp
#PI_TGT3    = pi-dyn

# RING (Send a trivial message around in a ring (MPI))
RING_TGT1  = ring-man
RING_TGT2  = ring-comp
#RING_TGT3  = ring-dyn

