# Stale bot: https://github.com/apps/stale
# Stale probot: https://probot.github.io/apps/stale/
# Main code repo: 

# Open MPI policy:
# - Warn of pending closure for issues/pull requests if there is no
#   activity on them for 90 days.
# - If there's no more activity for 7 more days, close the issue.
# - Never auto-close issues/pull requests with the label "pinned" or
#   "security" on them.

############################################################################

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed in 7 days if no further activity occurs.
  Thank you for your contributions!

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
