#! /bin/csh -f
#  Name
#  ====
#  run for mca ns tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               replica runs ompi ns replica tests

# Usage
#
# =====
# To invoke this script, enter either
#     run 
# with no arguments to run all tests, or
#     run <test_name>

umask 007

if ("x$1" == "x") then
  ./test_ns_replica;
else if ("$1" == "replica") then
  ./test_ns_replica;
else
  echo "correct use: "
  echo "    run    (to run all class tests)"
  echo "or  run < replica >"
  exit -1
endif


