#! /bin/csh -f
#  Name
#  ====
#  run script for mca ns tests

# Arguements
# ==========
# 
# test_list  =  no args or all runs all tests
#              or
#               test_ns_proxy runs ompi ns proxy tests
#               test_ns_replica runs ompi ns replica tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests  all
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  ./test_ns_proxy;
  ./test_ns_replica;
else 
  foreach target ($argv)
    switch ($target)
    case "all":
      ./test_ns_proxy;
      ./test_ns_replica;
      breaksw
    case "test_ns_replica":
    case "test_ns_proxy":
      ./$target;
      breaksw
    case "help":
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all   (to run all mca ns tests)"
      echo "or  run_tests with any of the following: "
      echo "               < test_ns_replica | test_ns_proxy >"
      break
      breaksw
    default
      echo "There is no test <$target> to run"
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all   (to run all mca ns tests)"
      echo "or  run_tests with any of the following: "
      echo "               < test_ns_replica | test_ns_proxy >"
      break
    endsw
  end
endif


