/* gm_config.h.  Generated by configure.  */
/* gm_config.h.in.  Generated from configure.ac by autoheader.  */

/* -*- c -*-
 *
 * Copyright (c) 2004-2005 The Trustees of Indiana University.
 *                         All rights reserved.
 * Copyright (c) 2004-2005 The Trustees of the University of Tennessee.
 *                         All rights reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart,
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 *
 * Open MPI configuation header file.
 * MCA btl: gm component
 */

#ifndef MCA_btl_gm_CONFIG_H
#define MCA_btl_gm_CONFIG_H


/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <gm.h> header file. */
#define HAVE_GM_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `gm' library (-lgm). */
#define HAVE_LIBGM 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Whether the gm btl is the default btl or not */
#define MCA_btl_gm_DEFAULT 0

/* OMPI architecture string */
#define OMPI_ARCH "i686-pc-linux-gnu"

/* OMPI underlying C compiler */
#define OMPI_CC "gcc"

/* Version of the GM API to use */
#define OMPI_MCA_BTL_GM_API_VERSION GM_API_VERSION

/* Disable GM BTL internal cache for registered memory */
#define OMPI_MCA_BTL_GM_CACHE_ENABLE 0

/* The GM build has or not a broker gm_get function */
#define OMPI_MCA_BTL_GM_GET_BROKEN 0

/* Whether we have get_get() or not */
#define OMPI_MCA_BTL_GM_HAVE_RDMA_GET 1

/* Whether we have gm_put() or gm_directed_send_with_callback() */
#define OMPI_MCA_BTL_GM_HAVE_RDMA_PUT 1

/* The OS support or not the virtal page registration */
#define OMPI_MCA_BTL_GM_SUPPORT_REGISTERING 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

#endif /* _MCA_btl_gm_CONFIG_H */
