#!/bin/bash
# Copyright (c) 2017 Amazon.com, Inc. or its affiliates.  All Rights
#                    reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI
#

mpirun -n 1 --mca reachable netlink reachable_netlink
mpirun -n 1 --mca reachable weighted reachable_weighted
