#!/bin/bash
# Copyright (c) 2017 Amazon.com, Inc. or its affiliates.  All Rights
#                    reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

mpirun -np 1 --mca reachable netlink reachable_netlink 
mpirun -np 1 --mca reachable weighted reachable_weighted 
