# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Currently, RTD needs to select an OS with OpenSSL>=1.1.1 because of
# urllib3's dependence on that system library.  (alternately, pin urllib3<2
# See https://github.com/urllib3/urllib3/issues/2168
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    # RTD doesn't run configure or make.  So we have to manually copy
    # in the PRRTE RST files to docs/.
    pre_create_environment:
      - ./.readthedocs-pre-create-environment.sh

python:
  install:
    - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

submodules:
  include: all
