dnl -*- shell-script -*-
dnl
dnl Copyright (c) 2004-2005 The Trustees of Indiana University.
dnl                         All rights reserved.
dnl Copyright (c) 2004-2005 The Trustees of the University of Tennessee.
dnl                         All rights reserved.
dnl Copyright (c) 2004-2005 High Performance Computing Center Stuttgart, 
dnl                         University of Stuttgart.  All rights reserved.
dnl Copyright (c) 2004-2005 The Regents of the University of California.
dnl                         All rights reserved.
dnl $COPYRIGHT$
dnl 
dnl Additional copyrights may follow
dnl 
dnl $HEADER$
dnl


#
# Open MPI-specific tests
#

m4_include(config/c_get_alignment.m4)
m4_include(config/c_weak_symbols.m4)

m4_include(config/cxx_find_template_parameters.m4)
m4_include(config/cxx_find_template_repository.m4)
m4_include(config/cxx_have_exceptions.m4)
m4_include(config/cxx_find_exception_flags.m4)

m4_include(config/f77_check.m4)
m4_include(config/f77_check_type.m4)
m4_include(config/f77_find_ext_symbol_convention.m4)
m4_include(config/f77_get_alignment.m4)
m4_include(config/f77_get_fortran_handle_max.m4)
m4_include(config/f77_get_sizeof.m4)
m4_include(config/f77_purge_unsupported_kind.m4)

m4_include(config/f90_check_type.m4)
m4_include(config/f90_find_module_include_flag.m4)
m4_include(config/f90_get_alignment.m4)
m4_include(config/f90_get_precision.m4)
m4_include(config/f90_get_range.m4)
m4_include(config/f90_get_sizeof.m4)
m4_include(config/f90_get_int_kind.m4)

m4_include(config/ompi_objc.m4)

m4_include(config/ompi_try_assemble.m4)
m4_include(config/ompi_config_asm.m4)

m4_include(config/ompi_case_sensitive_fs_setup.m4)
m4_include(config/ompi_check_broken_qsort.m4)
m4_include(config/ompi_check_optflags.m4)
m4_include(config/ompi_check_icc.m4)
m4_include(config/ompi_check_gm.m4)
m4_include(config/ompi_check_mx.m4)
m4_include(config/ompi_check_bproc.m4)
m4_include(config/ompi_check_mvapi.m4)
m4_include(config/ompi_check_openib.m4)
m4_include(config/ompi_check_package.m4)
m4_include(config/ompi_check_slurm.m4)
m4_include(config/ompi_check_tm.m4)
m4_include(config/ompi_check_xgrid.m4)
m4_include(config/ompi_config_subdir.m4)
m4_include(config/ompi_config_subdir_args.m4)
m4_include(config/ompi_configure_options.m4)
m4_include(config/ompi_find_type.m4)
m4_include(config/ompi_functions.m4)
m4_include(config/ompi_get_version.m4)
m4_include(config/ompi_get_libtool_linker_flags.m4)
m4_include(config/ompi_load_platform.m4)
m4_include(config/ompi_mca.m4)
m4_include(config/ompi_setup_cc.m4)
m4_include(config/ompi_setup_cxx.m4)
m4_include(config/ompi_setup_f77.m4)
m4_include(config/ompi_setup_f90.m4)
m4_include(config/ompi_setup_libevent.m4)
m4_include(config/ompi_make_stripped_flags.m4)

m4_include(config/ompi_check_pthread_pids.m4)
m4_include(config/ompi_config_pthreads.m4)
m4_include(config/ompi_config_solaris_threads.m4)
m4_include(config/ompi_config_threads.m4)

#
# The config/mca_no_configure_components.m4 file is generated by
# autogen.sh
#
m4_include(config/mca_no_configure_components.m4)

#
# mca_m4_config_include.m4 is generated by autogen.sh.  It includes
# the list of all component configure.m4 macros.
#
# Some explination... There doesn't seem to be a good way to have 
# this include file live in config/, because autoheader does it's
# analysis without taking into account the directory in which the .m4
# file calling m4_include is in, while autoconf does take the directory
# into account.  So you end up with a situation where you need two
# directories listed in the single m4_include.  If anyone knows a way
# to move mca_m4_config_include.m4 into config/, I'd appreciate it.
#
m4_include(mca_m4_config_include.m4)
