.TH fi_provider 7 "2015\-03\-31" "Libfabric Programmer\[aq]s Manual" "Libfabric v1.0.0rc5"
.SH NAME
.PP
Fabric Interface Providers
.SH OVERVIEW
.PP
Conceptually, a fabric provider may be viewed as a local hardware NIC
driver, though a provider is not limited by this definition.
The first component of libfabric is a general purpose framework that is
capable of handling different types of fabric hardware.
All fabric hardware devices and their software drivers are required to
support this framework.
Devices and the drivers that plug into the libfabric framework are
referred to as fabric providers, or simply providers.
.PP
This distribution of libfabric contains the following providers
(although more may be available via run-time plugins):
.PP
\f[I]PSM\f[] : High-speed InfiniBand networking from Intel.
See \f[C]fi_psm\f[](7) for more information.
.PP
\f[I]Sockets\f[] : A general purpose provider that can be used on any
network that supports TCP/UDP sockets.
This provider is not intended to provide performance improvements over
regular TCP/UDP sockets, but rather to allow developers to write, test,
and debug application code even on platforms that do not have high-speed
networking.
See \f[C]fi_sockets\f[](7) for more information.
.PP
\f[I]usNIC\f[] : Ultra low latency Ethernet networking over Cisco
userspace VIC adapters.
See \f[C]fi_usnic\f[](7) for more information.
.PP
\f[I]Verbs\f[] : This provider uses the Linux Verbs API for network
transport.
Application performance is, obviously expected to be similar to that of
the native Linux Verbs API.
Analogous to the Sockets provider, the Verbs provider is intended to
enable developers to write, test, and debug application code on
platforms that only have Linux Verbs-based networking.
See \f[C]fi_verbs\f[](7) for more information.
.SH PROVIDER REQUIREMENTS
.PP
Libfabric provides a general framework for supporting multiple types of
fabric objects and their related interfaces.
Fabric providers have a large amount of flexibility in selecting which
components they are able and willing to support, based on specific
hardware constraints.
To assist in the development of applications, libfabric specifies the
following requirements that must be met by any fabric provider, if
requested by an application.
(Note that the instantiation of a specific fabric object is subject to
application configuration parameters and need not meet these
requirements).
.IP \[bu] 2
A fabric provider must support at least one endpoint type.
.IP \[bu] 2
All endpoints must support the message queue data transfer interface.
.IP \[bu] 2
An endpoint that advertises support for a specific endpoint capability
must support the corresponding data transfer interface.
.IP \[bu] 2
Endpoints must support operations to send and receive data for any data
transfer operations that they support.
.IP \[bu] 2
Connectionless endpoints must support all relevant data transfer
routines.
(send / recv / write / read / etc.)
.IP \[bu] 2
Connectionless endpoints must support the CM interface getname.
.IP \[bu] 2
Connectionless endpoints that support multicast operations must support
the CM interfaces join and leave.
.IP \[bu] 2
Connection-oriented interfaces must support the CM interfaces getname,
getpeer, connect, listen, accept, reject, and shutdown.
.IP \[bu] 2
All endpoints must support all relevant \[aq]msg\[aq] data transfer
routines.
(sendmsg / recvmsg / writemsg / readmsg / etc.)
.IP \[bu] 2
Access domains must support opening address vector maps and tables.
.IP \[bu] 2
Address vectors associated with domains that may be identified using IP
addresses must support the FI_SOCKADDR_IN input format.
.IP \[bu] 2
Access domains must support opening completion queues and counters.
.IP \[bu] 2
Completion queues must support the FI_CQ_FORMAT_CONTEXT and
FI_CQ_FORMAT_MSG formats.
.IP \[bu] 2
Event queues associated with tagged message transfers must support the
FI_CQ_FORMAT_TAGGED format.
.IP \[bu] 2
A provider is expected to be forward compatible, and must be able to be
compiled against expanded \f[C]fi_xxx_ops\f[] structures that define new
functions added after the provider was written.
Any unknown functions must be set to NULL.
.SH LOGGING INTERFACE
.PP
Logging is performed using the FI_ERR, FI_LOG, and FI_DEBUG macros.
.SS DEFINITIONS
.IP
.nf
\f[C]
#define\ FI_ERR(prov_name,\ subsystem,\ ...)

#define\ FI_LOG(prov_name,\ prov,\ level,\ subsystem,\ ...)

#define\ FI_DEBUG(prov_name,\ subsystem,\ ...)
\f[]
.fi
.SS ARGUMENTS
.PP
\f[I]prov_name\f[] : String representing the provider name.
.PP
\f[I]prov\f[] : Provider context structure.
.PP
\f[I]level\f[] : Log level associated with log statement.
.PP
\f[I]subsystem\f[] : Subsystem being logged from.
.SS DESCRIPTION
.PP
\f[I]FI_ERR\f[] : Always logged.
.PP
\f[I]FI_LOG\f[] : Logged if the intended provider, log level, and
subsystem parameters match the user supplied values.
.PP
\f[I]FI_DEBUG\f[] : Logged if configured with the --enable-debug flag.
.SH SEE ALSO
.PP
\f[C]fi_psm\f[](7), \f[C]fi_sockets\f[](7), \f[C]fi_usnic\f[](7),
\f[C]fi_verbs\f[](7),
.SH AUTHORS
OpenFabrics.
