#ifndef TREEMATCH_RENAME
#define TREEMATCH_RENAME

#define FiboLink_ ompi_topo_treematch_FiboLink_
#define FiboLink ompi_topo_treematch_FiboLink

#define FiboNode_ ompi_topo_treematch_FiboNode_
#define FiboNode ompi_topo_treematch_FiboNode

#define FiboTree_ ompi_topo_treematch_FiboTree_
#define FiboTree ompi_topo_treematch_FiboTree

#define fiboTreeInit ompi_topo_treematch_fiboTreeInit
#define fiboTreeExit ompi_topo_treematch_fiboTreeExit
#define fiboTreeFree ompi_topo_treematch_fiboTreeFree
#define fiboTreeConsolidate ompi_topo_treematch_fiboTreeConsolidate
#define fiboTreeAdd ompi_topo_treematch_fiboTreeAdd
#define fiboTreeDel ompi_topo_treematch_fiboTreeDel
#define fiboTreeMin ompi_topo_treematch_fiboTreeMin
#define fiboTreeCheck ompi_topo_treematch_fiboTreeCheck
#define fiboTreeCheck2 ompi_topo_treematch_fiboTreeCheck2

#define int_CIVector_ ompi_topo_treematch_int_CIVector_
#define int_CIVector ompi_topo_treematch_int_CIVector

#define intCIV_isInitialized ompi_topo_treematch_intCIV_isInitialized
#define intCIV_init ompi_topo_treematch_intCIV_init
#define intCIV_exit ompi_topo_treematch_intCIV_exit
#define intCIV_set ompi_topo_treematch_intCIV_set
#define intCIV_get ompi_topo_treematch_intCIV_get

#define kPartitioning ompi_topo_treematch_kPartitioning

#define QueueElement_ ompi_topo_treematch_QueueElement_
#define QueueElement ompi_topo_treematch_QueueElement

#define PriorityQueue_ ompi_topo_treematch_PriorityQueue_
#define PriorityQueue ompi_topo_treematch_PriorityQueue

#define PQ_init ompi_topo_treematch_PQ_init
#define PQ_free ompi_topo_treematch_PQ_free
#define PQ_exit ompi_topo_treematch_PQ_exit
#define PQ_isEmpty ompi_topo_treematch_PQ_isEmpty
#define PQ_insertElement ompi_topo_treematch_PQ_insertElement
#define PQ_deleteElement ompi_topo_treematch_PQ_deleteElement
#define PQ_insert ompi_topo_treematch_PQ_insert
#define PQ_delete ompi_topo_treematch_PQ_delete
#define PQ_findMaxElement ompi_topo_treematch_PQ_findMaxElement
#define PQ_deleteMaxElement ompi_topo_treematch_PQ_deleteMaxElement
#define PQ_findMaxKey ompi_topo_treematch_PQ_findMaxKey
#define PQ_deleteMax ompi_topo_treematch_PQ_deleteMax
#define PQ_increaseElementKey ompi_topo_treematch_PQ_increaseElementKey
#define PQ_decreaseElementKey ompi_topo_treematch_PQ_decreaseElementKey
#define PQ_adjustElementKey ompi_topo_treematch_PQ_adjustElementKey
#define PQ_increaseKey ompi_topo_treematch_PQ_increaseKey
#define PQ_decreaseKey ompi_topo_treematch_PQ_decreaseKey
#define PQ_adjustKey ompi_topo_treematch_PQ_adjustKey

#define coord ompi_topo_treematch_coord
#define bucket_t ompi_topo_treematch_bucket_t
#define _bucket_list_t ompi_topo_treematch__bucket_list_t
#define bucket_grouping ompi_topo_treematch_bucket_grouping
#define try_add_edge ompi_topo_treematch_try_add_edge

#define _com_mat_t ompi_topo_treematch__com_mat_t
#define com_mat_t ompi_topo_treematch_com_mat_t
#define kpartition ompi_topo_treematch_kpartition
#define kpartition_build_tree_from_topology ompi_topo_treematch_kpartition_build_tree_from_topology

#define tm_malloc ompi_topo_treematch_tm_malloc
#define tm_calloc ompi_topo_treematch_tm_calloc
#define tm_realloc ompi_topo_treematch_tm_realloc
#define tm_free ompi_topo_treematch_tm_free
#define tm_mem_check ompi_topo_treematch_tm_mem_check

#define new_affinity_mat ompi_topo_treematch_new_affinity_mat
#define build_synthetic_proc_id ompi_topo_treematch_build_synthetic_proc_id
#define build_synthetic_topology ompi_topo_treematch_build_synthetic_topology
#define compute_nb_leaves_from_level ompi_topo_treematch_compute_nb_leaves_from_level
#define depth_first ompi_topo_treematch_depth_first
#define fill_tab ompi_topo_treematch_fill_tab
#define init_mat ompi_topo_treematch_init_mat
#define map_topology ompi_topo_treematch_map_topology
#define nb_leaves ompi_topo_treematch_nb_leaves
#define nb_lines ompi_topo_treematch_nb_lines
#define nb_processing_units ompi_topo_treematch_nb_processing_units
#define print_1D_tab ompi_topo_treematch_print_1D_tab
#define tm_compute_mapping ompi_topo_treematch_tm_compute_mapping
#define tm_free_affinity_mat ompi_topo_treematch_tm_free_affinity_mat
#define tm_load_aff_mat ompi_topo_treematch_tm_load_aff_mat
#define update_comm_speed ompi_topo_treematch_update_comm_speed
#define constraint_t ompi_topo_treematch_constraint_t

#define init_genrand ompi_topo_treematch_init_genrand
#define init_by_array ompi_topo_treematch_init_by_array
#define genrand_int32 ompi_topo_treematch_genrand_int32
#define genrand_int31 ompi_topo_treematch_genrand_int31
#define genrand_real1 ompi_topo_treematch_genrand_real1
#define genrand_real2 ompi_topo_treematch_genrand_real2
#define genrand_real3 ompi_topo_treematch_genrand_real3
#define genrand_res53 ompi_topo_treematch_genrand_res53

#define tm_free_solution ompi_topo_treematch_tm_free_solution
#define distance ompi_topo_treematch_distance
#define display_sol_sum_com ompi_topo_treematch_display_sol_sum_com
#define display_sol ompi_topo_treematch_display_sol
#define tm_display_solution ompi_topo_treematch_tm_display_solution
#define tm_display_other_heuristics ompi_topo_treematch_tm_display_other_heuristics
#define in_tab ompi_topo_treematch_in_tab
#define map_Packed ompi_topo_treematch_map_Packed
#define map_RR ompi_topo_treematch_map_RR
#define hash_asc ompi_topo_treematch_hash_asc
#define generate_random_sol ompi_topo_treematch_generate_random_sol
#define eval_sol ompi_topo_treematch_eval_sol
#define exchange ompi_topo_treematch_exchange
#define gain_exchange ompi_topo_treematch_gain_exchange
#define select_max ompi_topo_treematch_select_max
#define compute_gain ompi_topo_treematch_compute_gain
#define map_MPIPP ompi_topo_treematch_map_MPIPP

#define _work_t ompi_topo_treematch__work_t
#define work_t ompi_topo_treematch_work_t

#define local_thread_t ompi_topo_treematch_local_thread_t

#define _thread_pool_t ompi_topo_treematch__thread_pool_t
#define thread_pool_t ompi_topo_treematch_thread_pool_t

#define get_nb_threads ompi_topo_treematch_get_nb_threads
#define submit_work ompi_topo_treematch_submit_work
#define wait_work_completion ompi_topo_treematch_wait_work_completion
#define terminate_thread_pool ompi_topo_treematch_terminate_thread_pool
#define create_work ompi_topo_treematch_create_work
#define test_main ompi_topo_treematch_test_main
#define destroy_work ompi_topo_treematch_destroy_work

#define CLOCK_T ompi_topo_treematch_CLOCK_T

#define time_diff ompi_topo_treematch_time_diff
#define get_time ompi_topo_treematch_get_time

#define get_local_topo_with_hwloc ompi_topo_treematch_get_local_topo_with_hwloc
#define hwloc_to_tm ompi_topo_treematch_hwloc_to_tm
#define int_cmp_inc ompi_topo_treematch_int_cmp_inc
#define optimize_arity ompi_topo_treematch_optimize_arity
#define symetric ompi_topo_treematch_symetric
#define tgt_to_tm ompi_topo_treematch_tgt_to_tm
#define tm_display_arity ompi_topo_treematch_tm_display_arity
#define tm_display_topology ompi_topo_treematch_tm_display_topology
#define tm_free_topology ompi_topo_treematch_tm_free_topology
#define tm_load_topology ompi_topo_treematch_tm_load_topology
#define tm_optimize_topology ompi_topo_treematch_tm_optimize_topology
#define tm_topology_add_binding_constraints ompi_topo_treematch_tm_topology_add_binding_constraints
#define topo_nb_proc ompi_topo_treematch_topo_nb_proc
#define topology_arity ompi_topo_treematch_topology_arity
#define topology_constraints ompi_topo_treematch_topology_constraints
#define topology_cost ompi_topo_treematch_topology_cost
#define topology_numbering ompi_topo_treematch_topology_numbering
#define topology_to_arch ompi_topo_treematch_topology_to_arch
#define nb_processing_units ompi_topo_treematch_nb_processing_units

#define update_val ompi_topo_treematch_update_val
#define display_tab ompi_topo_treematch_display_tab
#define set_node ompi_topo_treematch_set_node

#define _group_list_t ompi_topo_treematch__group_list_t
#define group_list_t ompi_topo_treematch_group_list_t

#define adjacency_t ompi_topo_treematch_adjacency_t

#define _work_unit_t ompi_topo_treematch__work_unit_t
#define work_unit_t ompi_topo_treematch_work_unit_t

#define complete_obj_weight ompi_topo_treematch_complete_obj_weight

#endif // TREEMATCH_RENAME
