COMMONINCLUDES = \
	-I$(OTFMERGESRCDIR) \
	-I$(top_builddir)/otflib -I$(top_srcdir)/otflib \
	-I$(top_builddir)/otfauxlib -I$(top_srcdir)/otfauxlib

COMMONCFLAGS =
COMMONLDADD = $(top_builddir)/otflib/libotf.la
COMMONDEPENDENCIES = $(top_builddir)/otflib/libotf.la
COMMONSOURCES = \
	$(OTFMERGESRCDIR)/handler.h \
	$(OTFMERGESRCDIR)/handler.c \
	$(OTFMERGESRCDIR)/otfmerge.c

