#!/bin/sh

# Copyright (c) 2017      IBM Corporation. All rights reserved.


# if there's no perl, skip the test
perl -v > /dev/null 2>&1
if [ $? -ne 0 ] ; then exit 77 ; fi

# I wrote more in Makedefs.am about why I'm using ${srcdir} here. I suspect
# there's a more correct way to set up automake so the file is available,
# but nothing else has worked for me yet.

perl ${srcdir}/nmcheck_prefix.pl
