#
# Shared list of prototype files to avoid listing dependencies multiple times.
#

prototype_files = \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/accumulate_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/bsend_init_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/bsend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/buffer_attach_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/compare_and_swap_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/fetch_and_op_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iread_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iread_at_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iread_at_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iread_shared_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iread_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iwrite_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iwrite_at_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iwrite_at_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iwrite_shared_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_iwrite_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_all_begin_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_all_end_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_at_all_begin_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_at_all_end_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_at_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_at_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_ordered_begin_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_ordered_end_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_ordered_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_shared_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_read_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_all_begin_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_all_end_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_at_all_begin_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_at_all_end_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_at_all_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_at_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_ordered_begin_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_ordered_end_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_ordered_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_shared_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/file_write_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/free_mem_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/f_sync_reg_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/get_accumulate_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/get_address_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/get_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iallgather_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iallgatherv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iallreduce_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ialltoall_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ialltoallv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ialltoallw_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ibcast_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ibsend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iexscan_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/igather_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/igatherv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/imrecv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ineighbor_allgather_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ineighbor_allgatherv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ineighbor_alltoall_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ineighbor_alltoallv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ineighbor_alltoallw_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/irecv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ireduce_scatter_block_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ireduce_scatter_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ireduce_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/irsend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iscan_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iscatter_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/iscatterv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/isendrecv_replace_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/isendrecv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/isend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/issend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/mrecv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/pack_external_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/pack_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/put_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/raccumulate_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/recv_init_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/recv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/rget_accumulate_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/rget_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/rput_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/rsend_init_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/rsend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/send_init_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/sendrecv_replace_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/sendrecv_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/send_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ssend_init_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/ssend_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/unpack_external_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/unpack_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/win_attach_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/win_create_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/win_detach_ts.c.in

# Temporary variable while converting files.
ready_prototype_files = \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/send_ts.c.in \
        $(abs_top_srcdir)/ompi/mpi/fortran/use-mpi-f08/recv_ts.c.in
