# Copyright (c) 2013      Mellanox Technologies, Inc.
#                         All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI


headers += \
	oshmem/constants.h \
	oshmem/frameworks.h \
	oshmem/types.h

nodist_headers += \
	oshmem/version.h

