.TH fi_errno 3 "2015\-01\-08" "Libfabric Programmer\[aq]s Manual" "Libfabric v1.0.0rc5"
.SH NAME
.PP
fi_errno - fabric errors
.PP
fi_strerror - Convert fabric error into a printable string
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <rdma/fi_errno.h>

const\ char\ *fi_strerror(int\ errnum);
\f[]
.fi
.SH ERRORS
.PP
\f[I]FI_ENOENT\f[] : No such file or directory.
.PP
\f[I]FI_EIO\f[] : I/O error
.PP
\f[I]FI_E2BIG\f[] : Argument list too long.
.PP
\f[I]FI_EBADF\f[] : Bad file number.
.PP
\f[I]FI_EAGAIN\f[] : Try again.
.PP
\f[I]FI_ENOMEM\f[] : Out of memory.
.PP
\f[I]FI_EACCES\f[] : Permission denied.
.PP
\f[I]FI_EBUSY\f[] : Device or resource busy
.PP
\f[I]FI_ENODEV\f[] : No such device
.PP
\f[I]FI_EINVAL\f[] : Invalid argument
.PP
\f[I]FI_EMFILE\f[] : Too many open files
.PP
\f[I]FI_ENOSPC\f[] : No space left on device
.PP
\f[I]FI_ENOSYS\f[] : Function not implemented
.PP
\f[I]FI_ENOMSG\f[] : No message of desired type
.PP
\f[I]FI_ENODATA\f[] : No data available
.PP
\f[I]FI_EMSGSIZE\f[] : Message too long
.PP
\f[I]FI_ENOPROTOOPT\f[] : Protocol not available
.PP
\f[I]FI_EOPNOTSUPP\f[] : Operation not supported on transport endpoint
.PP
\f[I]FI_EADDRINUSE\f[] : Address already in use
.PP
\f[I]FI_EADDRNOTAVAIL\f[] : Cannot assign requested address
.PP
\f[I]FI_ENETDOWN\f[] : Network is down
.PP
\f[I]FI_ENETUNREACH\f[] : Network is unreachable
.PP
\f[I]FI_ECONNABORTED\f[] : Software caused connection abort
.PP
\f[I]FI_ECONNRESET\f[] : Connection reset by peer
.PP
\f[I]FI_EISCONN\f[] : Transport endpoint is already connected
.PP
\f[I]FI_ENOTCONN\f[] : Transport endpoint is not connected
.PP
\f[I]FI_ESHUTDOWN\f[] : Cannot send after transport endpoint shutdown
.PP
\f[I]FI_ETIMEDOUT\f[] : Operation timed out
.PP
\f[I]FI_ECONNREFUSED\f[] : Connection refused
.PP
\f[I]FI_EHOSTUNREACH\f[] : No route to host
.PP
\f[I]FI_EALREADY\f[] : Operation already in progress
.PP
\f[I]FI_EINPROGRESS\f[] : Operation now in progress
.PP
\f[I]FI_EREMOTEIO\f[] : Remote I/O error
.PP
\f[I]FI_ECANCELED\f[] : Operation Canceled
.PP
\f[I]FI_ENOKEY\f[] : Required key not available
.PP
\f[I]FI_EKEYREJECTED\f[] : Key was rejected by service
.PP
\f[I]FI_EOTHER\f[] : Unspecified error
.PP
\f[I]FI_ETOOSMALL\f[] : Provided buffer is too small
.PP
\f[I]FI_EOPBADSTATE\f[] : Operation not permitted in current state
.PP
\f[I]FI_EAVAIL\f[] : Error available
.PP
\f[I]FI_EBADFLAGS\f[] : Flags not supported
.PP
\f[I]FI_ENOEQ\f[] : Missing or unavailable event queue
.PP
\f[I]FI_EDOMAIN\f[] : Invalid resource domain
.PP
\f[I]FI_ENOCQ\f[] : Missing or unavailable completion queue
.SH SEE ALSO
.PP
\f[C]fabric\f[](7)
.SH AUTHORS
OpenFabrics.
