// -*- groovy -*-
//
// Copyright (c) 2022-2023 Amazon.com, Inc. or its affiliates.  All rights
//                         reserved.
// Copyright (c) 2022-2023 Joe Downs.  All rights reserved.
// Copyright (c) 2023      Cisco Systems, Inc.  All rights reserved.
// $COPYRIGHT$
//
// Additional copyrights may follow
//
// $HEADER$
//
// Build an Open MPI Pull Request
//
//
// WORKSPACE Layout:
//   autotools-install/    Autotools install for the builder
//   ompi/                 Open MPI source tree

// We if we push changes to a PR, we don't need to keep old jobs running, so
// we'll use the milestone step in Jenkins. Using an example from
// https://stackoverflow.com/questions/40760716/jenkins-abort-running-build-if-new-one-is-started:
//
// - Build 1 runs and creates milestone 1.
// - While build 1 is running, build 2 fires. It has milestone 1 and milestone
//   2. It passes milestone 1, which causes build 1 to abort.
def buildNumber = env.BUILD_NUMBER as int
if (buildNumber > 1) {
    milestone(buildNumber - 1)
}
milestone(buildNumber)

pipeline {
  stages {
    stage("Hi OMPI!") {
      steps {
        script {
          sh "echo hi"
          sh "while :; do echo 'Putting Jenkins in infinite loop'; sleep 1; done"
        }
      }
    }
  }
}
