#! /bin/csh -f
#  Name
#  ====
#  run script for util tests

# Arguements
# ==========
# 
# test_list  =  no args or all runs all tests
#              or
#               ompi_argv runs ompi_argv tests
#               ompi_numtostr runs ompi_numtostr tests
#               ompi_os_create_dirpath runs ompi_os_create_dirpath tests, 
#               ompi_os_path runs ompi_os_path tests, 
#               ompi_session_dir runs ompi_session_dir tests
#               ompi_sys_info runs ompi_sys_info tests
#               ompi_pack runs ompi_pack tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
#  ./ompi_argv
  ./ompi_numtostr
  ./ompi_os_create_dirpath
  ./ompi_pack
  ./ompi_os_path
#  ./ompi_session_dir
  ./ompi_sys_info
else
  foreach target ($argv)
    switch ($target)
    case "all":
#      ./ompi_argv
      ./ompi_numtostr
      ./ompi_os_create_dirpath
      ./ompi_pack
      ./ompi_os_path
#      ./ompi_session_dir
      ./ompi_sys_info
      breaksw
    case "ompi_argv":
    case "ompi_numtostr":
    case "ompi_os_create_dirpath":
    case "ompi_pack":
    case "ompi_os_path":
    case "ompi_session_dir":
    case "ompi_sys_info":
      ./$target
      breaksw
    case "help":
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all (to run all class tests)"
      echo "or  run_tests with any of the following: "
      echo "     <ompi_argv | ompi_numtostr | ompi_os_create_dirpath | "
      echo "      ompi_os_path | ompi_session_dir | ompi_sys_info>"
      break
      breaksw
    default
      echo "There is no test program <$target> to run"
      echo "correct use: "
      echo "    run_tests    (to run all class tests)"
      echo "or  run_tests with any of the following: "
      echo "     <ompi_argv | ompi_numtostr | ompi_os_create_dirpath | "
      echo "      ompi_os_path | ompi_session_dir | ompi_sys_info>"
      break
    endsw
  end
endif


