#! /bin/csh -f
#  Name
#  ====
#  run script for util tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               argv runs ompi_argv tests
#               numtostr runs ompi_numtostr tests
#               os_create_dirpath runs ompi_os_create_dirpath tests, 
#               os_path runs ompi_os_path tests, 
#               session_dir runs ompi_session_dir tests
#               sys_info runs ompi_sys_info tests
#               pack runs ompi_pack tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
#  ./ompi_argv
  ./ompi_numtostr
  ./ompi_os_create_dirpath
  ./ompi_pack
  ./ompi_os_path
#  ./ompi_session_dir
  ./ompi_sys_info
else if ("$1" == "argv") then
  ./ompi_argv
else if ("$1" == "numtostr") then
  ./ompi_numtostr
else if ("$1" == "os_create_dir_path") then
  ./ompi_os_create_dir_path
else if ("$1" == "os_path") then
  ./ompi_os_path
else if ("$1" == "pack") then
  ./ompi_pack
else if ("$1" == "session_dir") then
  ./ompi_session_dir
else if ("$1" == "sys_info") then
  ./ompi_sys_info
else
  echo "correct use: "
  echo "    run    (to run all class tests)"
  echo "or  run <argv | numtostr | os_create_dir_path | os_path | session_dir | sys_info>"
  exit -1
endif


