.\"
.\" Man page for OMPI's ompi-clean command
.\" 
.\" .TH name     section center-footer   left-footer  center-header
.TH     OMPI-CLEAN  1       "June 2006" "Open MPI"   "OPEN MPI COMMANDS"
.\" **************************
.\"    Name Section
.\" **************************
.SH NAME
.
ompi-clean, orte-clean \- Cleans up the Open Run Time Environment on all
accessible machines.
.
.PP
.
\fBNOTE:\fP \fIompi-clean\fP, and \fIorte-clean\fP are exact
synonyms for each other. Using any of the names will result in exactly
identical behavior.
.
.\" **************************
.\"    Synopsis Section
.\" **************************
.SH SYNOPSIS
.
.B ompi-clean
.R [ options ]
.
.\" **************************
.\"    Options Section
.\" **************************
.SH Options
.
To be written...
.
.
.\" **************************
.\"    Description Section
.\" **************************
.SH DESCRIPTION
.
.PP
\fIompi-clean\fR ...
.
.
.\" **************************
.\"    See Also Section
.\" **************************
.
.SH SEE ALSO
orterun(1)
.
