#! /bin/csh -f
#  Name
#  ====
#  run script for thread tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               ompi_condition runs ompi_condition tests
#               ompi_thread runs ompi_thread tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  ./ompi_thread
  ./ompi_condition
else 
  foreach target ($argv)
    switch ($target)
    case "all":
      ./ompi_condition
      ./ompi_thread
      breaksw
    case "ompi_condition":
      ./ompi_condition
      breaksw
    case "ompi_thread":
      ./ompi_thread
      breaksw
    case "help"
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all (to run all thread tests)"
      echo "or  run_tests and any of the following:"
      echo "      <omnpi_condition | ompi_thread>"
      break
      breaksw
    default:
      echo "There is no program <$target> to run"
      echo "correct use: "
      echo "    run_tests all (to run all thread tests)"
      echo "or  run_tests and any of the following:"
      echo "      <omnpi_condition | ompi_thread>"
      break
    endsw
  end
endif


