
#line 3 "util/hostfile/hostfile_lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE orte_util_hostfile_restart(orte_util_hostfile_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int orte_util_hostfile_leng;

extern FILE *orte_util_hostfile_in, *orte_util_hostfile_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up orte_util_hostfile_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up orte_util_hostfile_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via orte_util_hostfile_restart()), so that the user can continue scanning by
	 * just pointing orte_util_hostfile_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when orte_util_hostfile_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int orte_util_hostfile_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow orte_util_hostfile_wrap()'s to do buffer switches
 * instead of setting up a fresh orte_util_hostfile_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void orte_util_hostfile_restart (FILE *input_file  );
void orte_util_hostfile__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE orte_util_hostfile__create_buffer (FILE *file,int size  );
void orte_util_hostfile__delete_buffer (YY_BUFFER_STATE b  );
void orte_util_hostfile__flush_buffer (YY_BUFFER_STATE b  );
void orte_util_hostfile_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void orte_util_hostfile_pop_buffer_state (void );

static void orte_util_hostfile_ensure_buffer_stack (void );
static void orte_util_hostfile__load_buffer_state (void );
static void orte_util_hostfile__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER orte_util_hostfile__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE orte_util_hostfile__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE orte_util_hostfile__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE orte_util_hostfile__scan_bytes (yyconst char *bytes,int len  );

void *orte_util_hostfile_alloc (yy_size_t  );
void *orte_util_hostfile_realloc (void *,yy_size_t  );
void orte_util_hostfile_free (void *  );

#define yy_new_buffer orte_util_hostfile__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        orte_util_hostfile_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            orte_util_hostfile__create_buffer(orte_util_hostfile_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        orte_util_hostfile_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            orte_util_hostfile__create_buffer(orte_util_hostfile_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *orte_util_hostfile_in = (FILE *) 0, *orte_util_hostfile_out = (FILE *) 0;

typedef int yy_state_type;

extern int orte_util_hostfile_lineno;

int orte_util_hostfile_lineno = 1;

extern char *orte_util_hostfile_text;
#define yytext_ptr orte_util_hostfile_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up orte_util_hostfile_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	orte_util_hostfile_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[184] =
    {   0,
       31,   31,    5,    5,   37,   35,   10,    1,   35,   35,
       31,   35,   30,   31,   11,   31,   31,   31,   31,   31,
       31,   31,    5,    7,    6,   10,    1,    0,    9,    0,
        2,   31,    4,    0,   31,    0,   30,   31,   31,   31,
        0,   31,   31,   31,   34,   31,   31,   31,   31,   31,
       31,   31,    5,    6,    6,    8,    0,    3,    0,   30,
       31,   31,   31,   31,    0,    0,   31,   31,   31,   31,
       31,   31,   31,   12,   31,   31,   31,    0,    0,   30,
       31,   31,   31,   31,   31,    0,    0,   33,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,    0,    0,

       30,   31,   31,   31,    0,   33,   31,   31,   13,   31,
       31,   31,   31,   31,   31,   14,   31,   31,   31,    0,
        0,   31,   31,    0,   33,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   32,    0,   33,   31,   31,   19,   20,   31,   21,
       31,   31,   22,   31,   31,   31,   31,   31,   31,   32,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       27,   32,   23,   24,   25,   17,   26,   18,   15,   16,
       28,   29,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    1,    7,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
       13,    1,    1,   14,   15,   15,   15,   15,   15,   15,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        7,    7,    7,   17,   18,    7,   19,   15,   20,   15,

       21,   15,   16,   16,   16,   16,   16,   22,   23,   24,
       25,   26,   16,   27,   28,   29,   30,   16,   16,   31,
       16,   16,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[32] =
    {   0,
        1,    1,    2,    3,    1,    4,    5,    6,    7,    1,
        8,    9,    1,    5,    8,    6,    5,    6,    8,    8,
        8,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6
    } ;

static yyconst flex_int16_t yy_base[202] =
    {   0,
        0,    0,   29,   30,  386,  528,   35,  528,  381,  381,
        0,   33,   38,   66,  528,   82,  103,  119,   15,  360,
      356,  349,    0,  528,   65,   70,  528,  371,  528,  371,
      528,    0,  528,  370,  129,  357,  140,    0,  156,   65,
       30,  177,  188,    0,    0,  199,  215,  337,  336,  333,
      338,  341,    0,   73,   74,  528,  354,  528,  108,  222,
      119,  235,  251,  272,  344,  117,  283,    0,  294,  305,
      321,  328,  331,   74,  124,  324,  325,  340,  134,  123,
      334,  339,  143,    0,  350,  333,  135,  332,  361,  372,
      330,  312,  314,  313,  137,  138,  306,  182,  182,  323,

      320,  383,  321,  394,  317,  311,  310,  405,  138,  302,
      300,  169,  296,  176,  295,  197,  288,  287,  291,  297,
      202,  295,  294,  289,  288,  287,  274,  273,  264,  259,
      259,  258,  261,  255,  234,  236,  230,  229,  232,  230,
      225,  234,  231,  227,  219,  217,    0,    0,  211,    0,
      205,  207,    0,  201,  209,  207,  202,  201,  202,  206,
      185,  181,  175,  141,  124,   92,   85,   64,   30,   27,
        0,  528,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  528,  426,  435,  444,  450,  456,  465,  474,
      483,  490,  494,  499,  501,  508,  510,  512,  514,  516,

      518
    } ;

static yyconst flex_int16_t yy_def[202] =
    {   0,
      183,    1,  184,  184,  183,  183,  183,  183,  185,  186,
      187,  183,  183,  187,  183,  183,   16,  188,   16,   17,
       17,   17,  189,  183,  190,  183,  183,  185,  183,  186,
      183,  187,  183,  191,   13,  183,   13,   14,  183,   37,
      192,  187,   14,   17,  193,   16,  194,   17,   17,   17,
       17,   17,  189,  190,  190,  183,  191,  183,  183,   37,
       60,  187,  183,   63,  195,  196,   42,   43,   42,   16,
      194,   39,   17,   17,   17,   17,   17,  183,  183,   35,
       35,   62,   82,   64,   63,  197,  196,  198,   42,   42,
       17,   17,   17,   17,   17,   17,   17,   17,  183,  183,

       35,   82,  102,   63,  199,  200,  187,   42,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,  183,
      183,  187,   64,  183,  201,  187,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,  183,  183,  183,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,  183,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,  183,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,    0,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183
    } ;

static yyconst flex_int16_t yy_nxt[560] =
    {   0,
        6,    7,    8,    9,   10,   11,   11,   11,    6,   12,
       13,   14,   15,   11,   16,   17,   18,   11,   16,   19,
       16,   17,   20,   17,   17,   17,   17,   21,   17,   22,
       17,   24,   24,   41,   25,   25,   26,   27,   33,   48,
       49,   66,   34,   32,   32,   35,   36,  182,   37,   38,
      181,   39,   40,   35,   32,   35,   40,   40,   40,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   41,
       55,   26,   27,  183,   56,   61,   42,   43,  183,   55,
       42,   93,  183,   56,   42,   42,   42,   32,   32,   44,
       45,   94,   46,   38,  180,   39,   46,   44,   32,   44,

       46,   46,   46,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   32,  179,   78,   44,   79,  178,
       41,   44,   44,   44,   32,   32,   32,  183,   66,   81,
       32,   95,   32,  101,   38,   32,   32,  183,  183,   35,
       32,   96,   78,   35,  100,  127,   87,   35,   35,   35,
       60,  183,  177,  103,   61,  128,  112,  114,   61,   61,
       61,   32,   32,   32,  113,  115,   62,   38,  176,   32,
       63,   64,   32,   32,   63,   63,   63,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   67,   68,  117,
      120,   67,  121,  131,  132,   67,   67,   67,   69,  118,

      134,  135,   69,  175,  137,  119,   69,   69,   69,   70,
      120,  174,  143,   70,  138,  173,  172,   70,   70,   70,
       32,   32,  171,  170,  169,  168,   32,  167,   72,  166,
      165,   32,   80,  164,  163,  162,   81,  161,   87,  120,
       81,   81,   81,   36,  160,   82,   38,  159,  158,   83,
      157,  156,  155,   83,   83,   83,   32,   32,   84,   45,
      154,   85,   38,  153,   32,   85,   84,   32,   84,   85,
       85,   85,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   32,  152,  151,   84,  150,  149,  148,
       84,   84,   84,   89,  147,  146,  145,   89,   68,   87,

       87,   89,   89,   89,   90,   38,   38,  142,   90,  141,
      140,  139,   90,   90,   90,   91,  136,  133,  130,   91,
      129,   68,   87,   91,   91,   91,   32,   32,   87,  183,
      101,   78,   32,  116,   72,  111,  110,   32,   32,   32,
      109,   38,   64,   87,   87,   38,   64,   64,   64,  102,
       99,   98,   97,  103,   92,   87,   58,  103,  103,  103,
      104,   77,   76,   75,  104,   74,   73,   59,  104,  104,
      104,  107,   58,   31,   29,  107,   52,   51,   50,  107,
      107,  107,  108,   31,   29,  183,  108,  183,  183,  183,
      108,  108,  108,  122,  183,  183,  183,  122,  183,  183,

      183,  122,  122,  122,  123,  183,  183,  183,  123,  183,
      183,  183,  123,  123,  123,  126,  183,  183,  183,  126,
      183,  183,  183,  126,  126,  126,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   32,   32,   32,  183,   32,   32,   47,
       47,   47,  183,   47,   47,   53,  183,   53,  183,   53,
       53,   53,   53,   53,   54,  183,   54,   54,   54,   54,
       54,   54,   54,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   65,  183,  183,  183,  183,   65,   65,   45,

       45,   45,   71,   71,   71,  183,   71,   71,   86,   86,
       88,  183,  183,  183,  183,   88,   88,  105,  105,  106,
      106,  124,  124,  125,  125,  144,  144,    5,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183
    } ;

static yyconst flex_int16_t yy_chk[560] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,   41,    3,    4,    7,    7,   12,   19,
       19,   41,   12,   13,   13,   13,   13,  170,   13,   13,
      169,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   14,
       25,   26,   26,   40,   25,   40,   14,   14,   54,   55,
       14,   74,   54,   55,   14,   14,   14,   16,   16,   16,
       16,   74,   16,   16,  168,   16,   16,   16,   16,   16,

       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   17,   17,  167,   59,   17,   59,  166,
       66,   17,   17,   17,   18,   18,   18,   61,   66,   61,
       18,   75,   18,   80,   80,   18,   18,   35,   87,   35,
       35,   75,   79,   35,   79,  109,   87,   35,   35,   35,
       37,   83,  165,   83,   37,  109,   95,   96,   37,   37,
       37,   39,   39,   39,   95,   96,   39,   39,  164,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   42,   42,   98,
       99,   42,   99,  112,  112,   42,   42,   42,   43,   98,

      114,  114,   43,  163,  116,   98,   43,   43,   43,   46,
      121,  162,  121,   46,  116,  161,  160,   46,   46,   46,
       47,   47,  159,  158,  157,  156,   47,  155,   47,  154,
      152,   47,   60,  151,  149,  146,   60,  145,  144,  143,
       60,   60,   60,   62,  142,   62,   62,  141,  140,   62,
      139,  138,  137,   62,   62,   62,   63,   63,   63,   63,
      136,   63,   63,  135,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   64,   64,  134,  133,   64,  132,  131,  130,
       64,   64,   64,   67,  129,  128,  127,   67,  126,  125,

      124,   67,   67,   67,   69,  123,  122,  120,   69,  119,
      118,  117,   69,   69,   69,   70,  115,  113,  111,   70,
      110,  107,  106,   70,   70,   70,   71,   71,  105,  103,
      101,  100,   71,   97,   71,   94,   93,   71,   72,   72,
       92,   91,   72,   88,   86,   81,   72,   72,   72,   82,
       78,   77,   76,   82,   73,   65,   57,   82,   82,   82,
       85,   52,   51,   50,   85,   49,   48,   36,   85,   85,
       85,   89,   34,   30,   28,   89,   22,   21,   20,   89,
       89,   89,   90,   10,    9,    5,   90,    0,    0,    0,
       90,   90,   90,  102,    0,    0,    0,  102,    0,    0,

        0,  102,  102,  102,  104,    0,    0,    0,  104,    0,
        0,    0,  104,  104,  104,  108,    0,    0,    0,  108,
        0,    0,    0,  108,  108,  108,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  187,  187,  187,    0,  187,  187,  188,
      188,  188,    0,  188,  188,  189,    0,  189,    0,  189,
      189,  189,  189,  189,  190,    0,  190,  190,  190,  190,
      190,  190,  190,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  192,    0,    0,    0,    0,  192,  192,  193,

      193,  193,  194,  194,  194,    0,  194,  194,  195,  195,
      196,    0,    0,    0,    0,  196,  196,  197,  197,  198,
      198,  199,  199,  200,  200,  201,  201,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int orte_util_hostfile__flex_debug;
int orte_util_hostfile__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *orte_util_hostfile_text;
#line 1 "hostfile_lex.l"
#line 2 "hostfile_lex.l"
/*
 * Copyright (c) 2004-2005 The Trustees of Indiana University and Indiana
 *                         University Research and Technology
 *                         Corporation.  All rights reserved.
 * Copyright (c) 2004-2006 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart, 
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * $COPYRIGHT$
 * 
 * Additional copyrights may follow
 * 
 * $HEADER$
 */
#include "orte_config.h"

#include <stdio.h>
#if HAVE_UNISTD_H
#include <unistd.h>
#endif

#include "orte/util/hostfile/hostfile_lex.h"

/*
 * local functions
 */
#if defined(c_plusplus) || defined(__cplusplus)
extern "C" {
#endif  /* defined(c_plusplus) || defined(__cplusplus) */

int orte_util_hostfile_wrap(void);

#if defined(c_plusplus) || defined(__cplusplus)
}
#endif  /* defined(c_plusplus) || defined(__cplusplus) */

int orte_util_hostfile_wrap(void)
{
    orte_util_hostfile_done = true;
    return 1;
}

/*
 * global variables
 */
int orte_util_hostfile_line=1;
orte_hostfile_value_t orte_util_hostfile_value;
bool orte_util_hostfile_done = false;


#line 693 "util/hostfile/hostfile_lex.c"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int orte_util_hostfile_wrap (void );
#else
extern int orte_util_hostfile_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( orte_util_hostfile_text, orte_util_hostfile_leng, 1, orte_util_hostfile_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( orte_util_hostfile_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( orte_util_hostfile_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, orte_util_hostfile_in))==0 && ferror(orte_util_hostfile_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(orte_util_hostfile_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int orte_util_hostfile_lex (void);

#define YY_DECL int orte_util_hostfile_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after orte_util_hostfile_text and orte_util_hostfile_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 60 "hostfile_lex.l"


#line 850 "util/hostfile/hostfile_lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! orte_util_hostfile_in )
			orte_util_hostfile_in = stdin;

		if ( ! orte_util_hostfile_out )
			orte_util_hostfile_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			orte_util_hostfile_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				orte_util_hostfile__create_buffer(orte_util_hostfile_in,YY_BUF_SIZE );
		}

		orte_util_hostfile__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of orte_util_hostfile_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 184 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 528 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 62 "hostfile_lex.l"
{ orte_util_hostfile_line++; 
                     return ORTE_HOSTFILE_NEWLINE; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 64 "hostfile_lex.l"
{ orte_util_hostfile_line++; 
                     return ORTE_HOSTFILE_NEWLINE; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 66 "hostfile_lex.l"
{ orte_util_hostfile_line++; 
                     return ORTE_HOSTFILE_NEWLINE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 69 "hostfile_lex.l"
{ BEGIN(comment);
                     return ORTE_HOSTFILE_NEWLINE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 71 "hostfile_lex.l"
; /* Eat up non '*'s */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "hostfile_lex.l"
; /* Eat '*'s not followed by a '/' */
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 73 "hostfile_lex.l"
{ orte_util_hostfile_line++;
                     return ORTE_HOSTFILE_NEWLINE; } 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "hostfile_lex.l"
{ BEGIN(INITIAL); /* Done with Block Comment */
                     return ORTE_HOSTFILE_NEWLINE; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 78 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_QUOTED_STRING; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 81 "hostfile_lex.l"
;			/* whitespace */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "hostfile_lex.l"
{ return ORTE_HOSTFILE_EQUAL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 85 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_CPU; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_COUNT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 93 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 95 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 105 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 107 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 109 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 113 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_SLOTS_MAX; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text;
                     return ORTE_HOSTFILE_USERNAME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 118 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text;
                     return ORTE_HOSTFILE_USERNAME; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 120 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text;
                     return ORTE_HOSTFILE_USERNAME; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 123 "hostfile_lex.l"
{ orte_util_hostfile_value.ival = atol(orte_util_hostfile_text); 
                     return ORTE_HOSTFILE_INT; }
	YY_BREAK
 /* First detect hosts as standard Strings (but without ".")
    * then username@IPv4 or IPV4, then username@IPv6 or IPv6,
    * followed by username@hostname or hostname
    */

case 31:
YY_RULE_SETUP
#line 131 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text;
                     return ORTE_HOSTFILE_STRING; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 134 "hostfile_lex.l"
{
                      orte_util_hostfile_value.sval = orte_util_hostfile_text;
                      return ORTE_HOSTFILE_IPV4; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 138 "hostfile_lex.l"
{
                      orte_util_hostfile_value.sval = orte_util_hostfile_text;
                      return ORTE_HOSTFILE_IPV6; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 142 "hostfile_lex.l"
{
                     orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_HOSTNAME; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 146 "hostfile_lex.l"
{ orte_util_hostfile_value.sval = orte_util_hostfile_text; 
                     return ORTE_HOSTFILE_ERROR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 149 "hostfile_lex.l"
ECHO;
	YY_BREAK
#line 1157 "util/hostfile/hostfile_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed orte_util_hostfile_in at a new source and called
			 * orte_util_hostfile_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = orte_util_hostfile_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( orte_util_hostfile_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * orte_util_hostfile_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of orte_util_hostfile_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					orte_util_hostfile_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			orte_util_hostfile_restart(orte_util_hostfile_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 184 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 184 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 183);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up orte_util_hostfile_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					orte_util_hostfile_restart(orte_util_hostfile_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( orte_util_hostfile_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve orte_util_hostfile_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void orte_util_hostfile_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        orte_util_hostfile_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            orte_util_hostfile__create_buffer(orte_util_hostfile_in,YY_BUF_SIZE );
	}

	orte_util_hostfile__init_buffer(YY_CURRENT_BUFFER,input_file );
	orte_util_hostfile__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void orte_util_hostfile__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		orte_util_hostfile_pop_buffer_state();
	 *		orte_util_hostfile_push_buffer_state(new_buffer);
     */
	orte_util_hostfile_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	orte_util_hostfile__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (orte_util_hostfile_wrap()) processing, but the only time this flag
	 * is looked at is after orte_util_hostfile_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void orte_util_hostfile__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	orte_util_hostfile_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE orte_util_hostfile__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) orte_util_hostfile_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in orte_util_hostfile__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) orte_util_hostfile_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in orte_util_hostfile__create_buffer()" );

	b->yy_is_our_buffer = 1;

	orte_util_hostfile__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with orte_util_hostfile__create_buffer()
 * 
 */
    void orte_util_hostfile__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		orte_util_hostfile_free((void *) b->yy_ch_buf  );

	orte_util_hostfile_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a orte_util_hostfile_restart() or at EOF.
 */
    static void orte_util_hostfile__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	orte_util_hostfile__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then orte_util_hostfile__init_buffer was _probably_
     * called from orte_util_hostfile_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void orte_util_hostfile__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		orte_util_hostfile__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void orte_util_hostfile_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	orte_util_hostfile_ensure_buffer_stack();

	/* This block is copied from orte_util_hostfile__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from orte_util_hostfile__switch_to_buffer. */
	orte_util_hostfile__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void orte_util_hostfile_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	orte_util_hostfile__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		orte_util_hostfile__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void orte_util_hostfile_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)orte_util_hostfile_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)orte_util_hostfile_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE orte_util_hostfile__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) orte_util_hostfile_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in orte_util_hostfile__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	orte_util_hostfile__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to orte_util_hostfile_lex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       orte_util_hostfile__scan_bytes() instead.
 */
YY_BUFFER_STATE orte_util_hostfile__scan_string (yyconst char * yystr )
{
    
	return orte_util_hostfile__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to orte_util_hostfile_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE orte_util_hostfile__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) orte_util_hostfile_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in orte_util_hostfile__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = orte_util_hostfile__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in orte_util_hostfile__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up orte_util_hostfile_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		orte_util_hostfile_text[orte_util_hostfile_leng] = (yy_hold_char); \
		(yy_c_buf_p) = orte_util_hostfile_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		orte_util_hostfile_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int orte_util_hostfile_get_lineno  (void)
{
        
    return orte_util_hostfile_lineno;
}

/** Get the input stream.
 * 
 */
FILE *orte_util_hostfile_get_in  (void)
{
        return orte_util_hostfile_in;
}

/** Get the output stream.
 * 
 */
FILE *orte_util_hostfile_get_out  (void)
{
        return orte_util_hostfile_out;
}

/** Get the length of the current token.
 * 
 */
int orte_util_hostfile_get_leng  (void)
{
        return orte_util_hostfile_leng;
}

/** Get the current token.
 * 
 */

char *orte_util_hostfile_get_text  (void)
{
        return orte_util_hostfile_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void orte_util_hostfile_set_lineno (int  line_number )
{
    
    orte_util_hostfile_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see orte_util_hostfile__switch_to_buffer
 */
void orte_util_hostfile_set_in (FILE *  in_str )
{
        orte_util_hostfile_in = in_str ;
}

void orte_util_hostfile_set_out (FILE *  out_str )
{
        orte_util_hostfile_out = out_str ;
}

int orte_util_hostfile_get_debug  (void)
{
        return orte_util_hostfile__flex_debug;
}

void orte_util_hostfile_set_debug (int  bdebug )
{
        orte_util_hostfile__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from orte_util_hostfile_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    orte_util_hostfile_in = stdin;
    orte_util_hostfile_out = stdout;
#else
    orte_util_hostfile_in = (FILE *) 0;
    orte_util_hostfile_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * orte_util_hostfile_lex_init()
     */
    return 0;
}

/* orte_util_hostfile_lex_destroy is for both reentrant and non-reentrant scanners. */
int orte_util_hostfile_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		orte_util_hostfile__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		orte_util_hostfile_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	orte_util_hostfile_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * orte_util_hostfile_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *orte_util_hostfile_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *orte_util_hostfile_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void orte_util_hostfile_free (void * ptr )
{
	free( (char *) ptr );	/* see orte_util_hostfile_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 149 "hostfile_lex.l"



