#! /bin/csh -f
#  Name
#  ====
#  run for mca llm base tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               parse_hostfile runs ompi llm base parse_hostfile tests

# Usage
#
# =====
# To invoke this script, enter either
#     run 
# with no arguments to run all tests, or
#     run <test_name>

umask 007

if ("x$1" == "x") then
  ./parse_hostfile;
else 
  foreach target ($argv)
    switch ($target)
    case "all"
      ./parse_hostfile
      breaksw
    case "parse_hostfile":
      ./$target
      breaksw
    case "help":
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all   (to run all class tests)"
      echo "or  run_tests < parse_hostfile >"
      break
      breaksw
    default:
      echo "There is no test program <$target> to run."
      echo "    run_tests all   (to run all class tests)"
      echo "or  run_tests < parse_hostfile >"
      break
    endsw
  end
endif


