#
# Makefile.am for the onesided part component
#

onesided_sources = part_onesided.c part_onesided_component.c part_onesided_request.c part_onesided_control.c part_onesided_match.c

libpart_onesided_la_sources = onesided_sources
libpart_onesided_la_LDFLAGS = $(libtool_modulize_flag)
libpart_onesided_la_libdir = $(libdir)
