#
# Copyright (c) 2016      Mellanox Technologies, Inc.
#                         All rights reserved.
# Copyright (c) 2016      Intel, Inc.  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

headers += \
        sm/pmix_sm.h \
        sm/pmix_mmap.h

sources += \
        sm/pmix_sm.c \
        sm/pmix_mmap.c
