#! /bin/csh -f
#  Name
#  ====
#  run script for mca tests

# Arguements
# ==========
# 
# test_list  =  no args or all runs all tests
#              or
#               llm runs ompi mca llm tests
#               ns runs ompi mca ns tests
#               oob runs ompi mca oob tests 
#               pcm runs ompi mca pcm tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  cd gpr; ./run_tests all;
  cd llm; ./run_tests all;
#  cd ../ns;  ./run_tests all;
  cd ../oob; ./run_tests all;
  cd ../pcm; ./run_tests all;
  cd ..;
else

  foreach target ($argv)
    switch ($target)
    case "all":
      cd llm; ./run_tests all;
#      cd ../ns;  ./run_tests all;
      cd ../oob; ./run_tests all;
      cd ../pcm; ./run_tests all;
      cd ..;
      breaksw
    case "gpr":
    case "llm":
#    case "ns":
    case "oob":
    case "pcm":
      cd $target
      ./run_tests;
      cd ..;
      breaksw
    case "help":
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all  (to run all mca tests)"
      echo "or  run_tests <llm | ns | oob | pcm>"
      breaksw
    default
      echo "There is no part of mca called program <$target> to run"
      echo "correct use: "
      echo "    run_tests all   (to run all mca tests)"
      echo "or  run_tests <llm | ns | oob | pcm>"
      break
    endsw
  end

endif


