variables:
  SCHEDULER_PARAMETERS: "-pgeneral -t 4:00:00 -N 1 --ntasks-per-node=16"
  GIT_STRATEGY: clone
  NPROCS: 4

stages:
  - build
  - test

build:intel:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov
  stage: build
  tags: [darwin-slurm-shared]
  script:
    - module load intel/2022.0.1
    - rm .gitmodules
    - cp $GITSUBMODULEPATCH .gitmodules
    - git submodule update --init --recursive
    - ./autogen.pl
    - ./configure CC=icx FC=ifx CXX=icpx --prefix=$PWD/install_test --with-libevent=internal
    - make -j 8 install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples
      - install_test
    expire_in: 1 week

build:amd:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov
  stage: build
  tags: [darwin-slurm-shared]
  variables:
    SCHEDULER_PARAMETERS: "-pamd-rome -t 4:00:00 -N 1 --ntasks-per-node=16"
  script:
    - module load aocc/3.0.0
    - rm .gitmodules
    - cp $GITSUBMODULEPATCH .gitmodules
    - git submodule update --init --recursive
    - ./autogen.pl
    - ./configure CC=clang FC=flang CXX=clang++ --prefix=$PWD/install_test --with-libevent=internal LIBS="-lucm -lucs"
    - make -j 8 install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples
      - install_test
    expire_in: 1 week

build:gnu:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov
  stage: build
  tags: [darwin-slurm-shared]
  script:
    - module load gcc
    - rm .gitmodules
    - cp $GITSUBMODULEPATCH .gitmodules
    - git submodule update --init --recursive
    - ./autogen.pl
    - ./configure --prefix=$PWD/install_test --with-libevent=internal
    - make -j 8 install
    - make check
    - export PATH=$PWD/install_test/bin:$PATH
    - cd examples
    - make
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    untracked: true
    paths:
      - examples
      - install_test
    expire_in: 1 week

test:intel:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov
  stage: test
  tags: [darwin-slurm-shared]
  dependencies:
    - build:intel
  needs: ["build:intel"]
  script:
    - pwd
    - ls
    - module load intel/2022.0.1
    - export PATH=$PWD/install_test/bin:$PATH
    - which mpirun
    - cd examples
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 week

test:amd:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov
  stage: test
  tags: [darwin-slurm-shared]
  variables:
    SCHEDULER_PARAMETERS: "-pamd-rome -t 2:00:00 -N 1 --ntasks-per-node=16"
  dependencies:
    - build:amd
  needs: ["build:amd"]
  script:
    - pwd
    - ls
    - module load aocc/3.0.0
    - export PATH=$PWD/install_test/bin:$PATH
    - export LD_LIBRARY_PATH=$PWD/install_test/lib:$LD_LIBRARY_PATH
    - which mpirun
    - cd examples
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 week

test:gnu:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://re-git.lanl.gov
  stage: test
  tags: [darwin-slurm-shared]
  dependencies:
    - build:gnu
  needs: ["build:gnu"]
  script:
    - pwd
    - ls
    - module load gcc
    - export PATH=$PWD/install_test/bin:$PATH
    - which mpirun
    - cd examples
    - mpirun -np 4 hostname
    - mpirun -np 4 ./hello_c
    - mpirun -np 4 ./ring_c
    - mpirun -np 4 ./hello_mpifh
    - mpirun -np 4 ./ring_mpifh
    - mpirun -np 4 ./hello_usempi
    - mpirun -np 4 ./ring_usempi
    - mpirun -np 4 ./hello_usempif08
    - mpirun -np 4 ./ring_usempif08
    - mpirun -np 4 ./connectivity_c
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 1 week

