.TH "hwloc_obj_attr_u" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_bridge_attr_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_cache_attr_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_group_attr_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_numanode_attr_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_osdev_attr_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_pcidev_attr_s\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_numanode_attr_s\fP \fBnumanode\fP"
.br
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_cache_attr_s\fP \fBcache\fP"
.br
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_group_attr_s\fP \fBgroup\fP"
.br
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_pcidev_attr_s\fP \fBpcidev\fP"
.br
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_bridge_attr_s\fP \fBbridge\fP"
.br
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_osdev_attr_s\fP \fBosdev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object type-specific Attributes\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBhwloc_obj_attr_u::hwloc_bridge_attr_s\fP  hwloc_obj_attr_u::bridge"

.SS "struct \fBhwloc_obj_attr_u::hwloc_cache_attr_s\fP  hwloc_obj_attr_u::cache"

.SS "struct \fBhwloc_obj_attr_u::hwloc_group_attr_s\fP  hwloc_obj_attr_u::group"

.SS "struct \fBhwloc_obj_attr_u::hwloc_numanode_attr_s\fP  hwloc_obj_attr_u::numanode"

.SS "struct \fBhwloc_obj_attr_u::hwloc_osdev_attr_s\fP  hwloc_obj_attr_u::osdev"

.SS "struct \fBhwloc_obj_attr_u::hwloc_pcidev_attr_s\fP  hwloc_obj_attr_u::pcidev"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
