.TH "hwlocality_generic_components" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwlocality_generic_components
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_component\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBhwloc_component_type_e\fP \fBhwloc_component_type_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBhwloc_component_type_e\fP { \fBHWLOC_COMPONENT_TYPE_DISC\fP, \fBHWLOC_COMPONENT_TYPE_XML\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBhwloc_component_type_e\fP  \fBhwloc_component_type_t\fP"

.PP
Generic component type\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBhwloc_component_type_e\fP"

.PP
Generic component type\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHWLOC_COMPONENT_TYPE_DISC \fP\fP
The data field must point to a struct \fBhwloc_disc_component\fP\&. 
.TP
\fB\fIHWLOC_COMPONENT_TYPE_XML \fP\fP
The data field must point to a struct hwloc_xml_component\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
