.TH "hwloc_obj_attr_u::hwloc_numanode_attr_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_numanode_attr_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_memory_page_type_s\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "hwloc_uint64_t \fBlocal_memory\fP"
.br
.ti -1c
.RI "unsigned \fBpage_types_len\fP"
.br
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_numanode_attr_s::hwloc_memory_page_type_s\fP * \fBpage_types\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
NUMA node-specific Object Attributes\&. 
.SH "Field Documentation"
.PP 
.SS "hwloc_uint64_t hwloc_obj_attr_u::hwloc_numanode_attr_s::local_memory"

.PP
Local memory (in bytes) 
.SS "struct \fBhwloc_obj_attr_u::hwloc_numanode_attr_s::hwloc_memory_page_type_s\fP *  hwloc_obj_attr_u::hwloc_numanode_attr_s::page_types"

.SS "unsigned hwloc_obj_attr_u::hwloc_numanode_attr_s::page_types_len"

.PP
Size of array \fCpage_types\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
