.TH "hwlocality_openfabrics" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwlocality_openfabrics
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBhwloc_ibv_get_device_cpuset\fP (\fBhwloc_topology_t\fP topology, struct ibv_device *ibdev, \fBhwloc_cpuset_t\fP set)"
.br
.ti -1c
.RI "static \fBhwloc_obj_t\fP \fBhwloc_ibv_get_device_osdev_by_name\fP (\fBhwloc_topology_t\fP topology, const char *ibname)"
.br
.ti -1c
.RI "static \fBhwloc_obj_t\fP \fBhwloc_ibv_get_device_osdev\fP (\fBhwloc_topology_t\fP topology, struct ibv_device *ibdev)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This interface offers ways to retrieve topology information about OpenFabrics devices (InfiniBand, Omni-Path, usNIC, etc)\&. 
.SH "Function Documentation"
.PP 
.SS "static int hwloc_ibv_get_device_cpuset (\fBhwloc_topology_t\fP topology, struct ibv_device * ibdev, \fBhwloc_cpuset_t\fP set)\fC [inline]\fP, \fC [static]\fP"

.PP
Get the CPU set of logical processors that are physically close to device \fCibdev\fP\&. Return the CPU set describing the locality of the OpenFabrics device \fCibdev\fP (InfiniBand, etc)\&.
.PP
Topology \fCtopology\fP and device \fCibdev\fP must match the local machine\&. I/O devices detection is not needed in the topology\&.
.PP
The function only returns the locality of the device\&. If more information about the device is needed, OS objects should be used instead, see \fBhwloc_ibv_get_device_osdev()\fP and \fBhwloc_ibv_get_device_osdev_by_name()\fP\&.
.PP
This function is currently only implemented in a meaningful way for Linux; other systems will simply get a full cpuset\&. 
.SS "static \fBhwloc_obj_t\fP hwloc_ibv_get_device_osdev (\fBhwloc_topology_t\fP topology, struct ibv_device * ibdev)\fC [inline]\fP, \fC [static]\fP"

.PP
Get the hwloc OS device object corresponding to the OpenFabrics device \fCibdev\fP\&. Return the OS device object describing the OpenFabrics device \fCibdev\fP (InfiniBand, etc)\&. Returns NULL if there is none\&.
.PP
Topology \fCtopology\fP and device \fCibdev\fP must match the local machine\&. I/O devices detection must be enabled in the topology\&. If not, the locality of the object may still be found using \fBhwloc_ibv_get_device_cpuset()\fP\&.
.PP
\fBNote:\fP
.RS 4
The corresponding PCI device object can be obtained by looking at the OS device parent object\&. 
.RE
.PP

.SS "static \fBhwloc_obj_t\fP hwloc_ibv_get_device_osdev_by_name (\fBhwloc_topology_t\fP topology, const char * ibname)\fC [inline]\fP, \fC [static]\fP"

.PP
Get the hwloc OS device object corresponding to the OpenFabrics device named \fCibname\fP\&. Return the OS device object describing the OpenFabrics device (InfiniBand, Omni-Path, usNIC, etc) whose name is \fCibname\fP (mlx5_0, hfi1_0, usnic_0, qib0, etc)\&. Returns NULL if there is none\&. The name \fCibname\fP is usually obtained from ibv_get_device_name()\&.
.PP
The topology \fCtopology\fP does not necessarily have to match the current machine\&. For instance the topology may be an XML import of a remote host\&. I/O devices detection must be enabled in the topology\&.
.PP
\fBNote:\fP
.RS 4
The corresponding PCI device object can be obtained by looking at the OS device parent object\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
