.TH "hwloc_topology_diff_obj_attr_u" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_diff_obj_attr_u
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_generic_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_string_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_uint64_s\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_generic_s\fP \fBgeneric\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s\fP \fBuint64\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s\fP \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One object attribute difference\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBhwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_generic_s\fP  hwloc_topology_diff_obj_attr_u::generic"

.SS "struct \fBhwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s\fP  hwloc_topology_diff_obj_attr_u::string"

.SS "struct \fBhwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s\fP  hwloc_topology_diff_obj_attr_u::uint64"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
