.TH "hwloc_obj_attr_u::hwloc_osdev_attr_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_osdev_attr_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhwloc_obj_osdev_type_t\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OS Device specific Object Attributes\&. 
.SH "Field Documentation"
.PP 
.SS "\fBhwloc_obj_osdev_type_t\fP hwloc_obj_attr_u::hwloc_osdev_attr_s::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
