.TH "hwloc_info_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_info_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object info\&. 


.PP
\fBSee also:\fP
.RS 4
\fBConsulting and Adding Key-Value Info Attributes\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "char* hwloc_info_s::name"

.PP
Info name\&. 
.SS "char* hwloc_info_s::value"

.PP
Info value\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
