.TH "hwloc_topology_cpubind_support" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_cpubind_support
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBset_thisproc_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBget_thisproc_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBset_proc_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBget_proc_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBset_thisthread_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBget_thisthread_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBset_thread_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBget_thread_cpubind\fP"
.br
.ti -1c
.RI "unsigned char \fBget_thisproc_last_cpu_location\fP"
.br
.ti -1c
.RI "unsigned char \fBget_proc_last_cpu_location\fP"
.br
.ti -1c
.RI "unsigned char \fBget_thisthread_last_cpu_location\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Flags describing actual PU binding support for this topology\&. 

A flag may be set even if the feature isn't supported in all cases (e\&.g\&. binding to random sets of non-contiguous objects)\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned char hwloc_topology_cpubind_support::get_proc_cpubind"
Getting the binding of a whole given process is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::get_proc_last_cpu_location"
Getting the last processors where a whole process ran is supported 
.SS "unsigned char hwloc_topology_cpubind_support::get_thisproc_cpubind"
Getting the binding of the whole current process is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::get_thisproc_last_cpu_location"
Getting the last processors where the whole current process ran is supported 
.SS "unsigned char hwloc_topology_cpubind_support::get_thisthread_cpubind"
Getting the binding of the current thread only is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::get_thisthread_last_cpu_location"
Getting the last processors where the current thread ran is supported 
.SS "unsigned char hwloc_topology_cpubind_support::get_thread_cpubind"
Getting the binding of a given thread only is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::set_proc_cpubind"
Binding a whole given process is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::set_thisproc_cpubind"
Binding the whole current process is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::set_thisthread_cpubind"
Binding the current thread only is supported\&. 
.SS "unsigned char hwloc_topology_cpubind_support::set_thread_cpubind"
Binding a given thread only is supported\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
