.TH "hwloc_topology_diff_u" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_diff_u
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_topology_diff_generic_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_obj_attr_s\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_too_complex_s\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBhwloc_topology_diff_u::hwloc_topology_diff_generic_s\fP \fBgeneric\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s\fP \fBobj_attr\fP"
.br
.ti -1c
.RI "struct \fBhwloc_topology_diff_u::hwloc_topology_diff_too_complex_s\fP \fBtoo_complex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
One element of a difference list between two topologies\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBhwloc_topology_diff_u::hwloc_topology_diff_generic_s\fP  hwloc_topology_diff_u::generic"

.SS "struct \fBhwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s\fP  hwloc_topology_diff_u::obj_attr"

.SS "struct \fBhwloc_topology_diff_u::hwloc_topology_diff_too_complex_s\fP  hwloc_topology_diff_u::too_complex"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
