.TH "hwloc_obj_attr_u::hwloc_group_attr_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_group_attr_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBdepth\fP"
.br
.ti -1c
.RI "unsigned \fBkind\fP"
.br
.ti -1c
.RI "unsigned \fBsubkind\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Group-specific Object Attributes\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned hwloc_obj_attr_u::hwloc_group_attr_s::depth"

.PP
Depth of group object\&. It may change if intermediate Group objects are added\&. 
.SS "unsigned hwloc_obj_attr_u::hwloc_group_attr_s::kind"

.PP
Internally-used kind of group\&. 
.SS "unsigned hwloc_obj_attr_u::hwloc_group_attr_s::subkind"

.PP
Internally-used subkind to distinguish different levels of groups with same kind\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
