.TH "hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhwloc_topology_diff_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "union \fBhwloc_topology_diff_u\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBobj_depth\fP"
.br
.ti -1c
.RI "unsigned \fBobj_index\fP"
.br
.ti -1c
.RI "union \fBhwloc_topology_diff_obj_attr_u\fP \fBdiff\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "union \fBhwloc_topology_diff_obj_attr_u\fP hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s::diff"

.SS "union \fBhwloc_topology_diff_u\fP* hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s::next"

.SS "int hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s::obj_depth"

.SS "unsigned hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s::obj_index"

.SS "\fBhwloc_topology_diff_type_t\fP hwloc_topology_diff_u::hwloc_topology_diff_obj_attr_s::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
