.TH "hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_generic_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_generic_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhwloc_topology_diff_obj_attr_type_t\fP \fBtype\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBhwloc_topology_diff_obj_attr_type_t\fP hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_generic_s::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
