.TH "hwlocality_components_filtering" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwlocality_components_filtering
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBhwloc_filter_check_pcidev_subtype_important\fP (unsigned classid)"
.br
.ti -1c
.RI "static int \fBhwloc_filter_check_osdev_subtype_important\fP (\fBhwloc_obj_osdev_type_t\fP subtype)"
.br
.ti -1c
.RI "static int \fBhwloc_filter_check_keep_object_type\fP (\fBhwloc_topology_t\fP topology, \fBhwloc_obj_type_t\fP type)"
.br
.ti -1c
.RI "static int \fBhwloc_filter_check_keep_object\fP (\fBhwloc_topology_t\fP topology, \fBhwloc_obj_t\fP obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "static int hwloc_filter_check_keep_object (\fBhwloc_topology_t\fP topology, \fBhwloc_obj_t\fP obj)\fC [inline]\fP, \fC [static]\fP"

.PP
Check whether the given object should be filtered-out\&. 
.PP
\fBReturns:\fP
.RS 4
1 if the object type should be kept, 0 otherwise\&. 
.RE
.PP

.SS "static int hwloc_filter_check_keep_object_type (\fBhwloc_topology_t\fP topology, \fBhwloc_obj_type_t\fP type)\fC [inline]\fP, \fC [static]\fP"

.PP
Check whether a non-I/O object type should be filtered-out\&. Cannot be used for I/O objects\&.
.PP
\fBReturns:\fP
.RS 4
1 if the object type should be kept, 0 otherwise\&. 
.RE
.PP

.SS "static int hwloc_filter_check_osdev_subtype_important (\fBhwloc_obj_osdev_type_t\fP subtype)\fC [inline]\fP, \fC [static]\fP"

.PP
Check whether the given OS device subtype is important\&. 
.PP
\fBReturns:\fP
.RS 4
1 if important, 0 otherwise\&. 
.RE
.PP

.SS "static int hwloc_filter_check_pcidev_subtype_important (unsigned classid)\fC [inline]\fP, \fC [static]\fP"

.PP
Check whether the given PCI device classid is important\&. 
.PP
\fBReturns:\fP
.RS 4
1 if important, 0 otherwise\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
