.TH "hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhwloc_topology_diff_obj_attr_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "hwloc_uint64_t \fBindex\fP"
.br
.ti -1c
.RI "hwloc_uint64_t \fBoldvalue\fP"
.br
.ti -1c
.RI "hwloc_uint64_t \fBnewvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Integer attribute modification with an optional index\&. 
.SH "Field Documentation"
.PP 
.SS "hwloc_uint64_t hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s::index"

.SS "hwloc_uint64_t hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s::newvalue"

.SS "hwloc_uint64_t hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s::oldvalue"

.SS "\fBhwloc_topology_diff_obj_attr_type_t\fP hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_uint64_s::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
