.TH "hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhwloc_topology_diff_obj_attr_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBoldvalue\fP"
.br
.ti -1c
.RI "char * \fBnewvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
String attribute modification with an optional name\&. 
.SH "Field Documentation"
.PP 
.SS "char* hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s::name"

.SS "char* hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s::newvalue"

.SS "char* hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s::oldvalue"

.SS "\fBhwloc_topology_diff_obj_attr_type_t\fP hwloc_topology_diff_obj_attr_u::hwloc_topology_diff_obj_attr_string_s::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
