.TH "hwloc_obj_attr_u::hwloc_pcidev_attr_s" 3 "Mon Feb 5 2018" "Version 2.0.0" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_pcidev_attr_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBdomain\fP"
.br
.ti -1c
.RI "unsigned char \fBbus\fP"
.br
.ti -1c
.RI "unsigned char \fBdev\fP"
.br
.ti -1c
.RI "unsigned char \fBfunc\fP"
.br
.ti -1c
.RI "unsigned short \fBclass_id\fP"
.br
.ti -1c
.RI "unsigned short \fBvendor_id\fP"
.br
.ti -1c
.RI "unsigned short \fBdevice_id\fP"
.br
.ti -1c
.RI "unsigned short \fBsubvendor_id\fP"
.br
.ti -1c
.RI "unsigned short \fBsubdevice_id\fP"
.br
.ti -1c
.RI "unsigned char \fBrevision\fP"
.br
.ti -1c
.RI "float \fBlinkspeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PCI Device specific Object Attributes\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned char hwloc_obj_attr_u::hwloc_pcidev_attr_s::bus"

.SS "unsigned short hwloc_obj_attr_u::hwloc_pcidev_attr_s::class_id"

.SS "unsigned char hwloc_obj_attr_u::hwloc_pcidev_attr_s::dev"

.SS "unsigned short hwloc_obj_attr_u::hwloc_pcidev_attr_s::device_id"

.SS "unsigned short hwloc_obj_attr_u::hwloc_pcidev_attr_s::domain"

.SS "unsigned char hwloc_obj_attr_u::hwloc_pcidev_attr_s::func"

.SS "float hwloc_obj_attr_u::hwloc_pcidev_attr_s::linkspeed"

.SS "unsigned char hwloc_obj_attr_u::hwloc_pcidev_attr_s::revision"

.SS "unsigned short hwloc_obj_attr_u::hwloc_pcidev_attr_s::subdevice_id"

.SS "unsigned short hwloc_obj_attr_u::hwloc_pcidev_attr_s::subvendor_id"

.SS "unsigned short hwloc_obj_attr_u::hwloc_pcidev_attr_s::vendor_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
