#! /bin/csh -f
#  Name
#  ====
#  run script for class tests

# Arguements
# ==========
# 
# test_list  =  no args or all runs all tests
#              or
#               ompi_bitmap runs ompi_bitmap tests
#               ompi_hash_list runs ompi_hash_list tests
#               ompi_pointer_array runs ompi_pointer_array tests, 
#               ompi_rb_tree runs ompi_rb_tree tests
#               ompi_value_array runs ompi_value_array tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if  ("x$1" == "x") then
  echo "do all - no args"
  ./ompi_bitmap
  ./ompi_hash_table
  ./ompi_list
  ./ompi_pointer_array
  ./ompi_rb_tree
  ./ompi_value_array
else 
  foreach target ($argv)
    switch ($target)
    case "all":
      ./ompi_bitmap
      ./ompi_hash_table
      ./ompi_list
      ./ompi_pointer_array
      ./ompi_rb_tree
      ./ompi_value_array
      breaksw
    case "ompi_bitmap":
    case "ompi_hash_table":
    case "ompi_pointer_array":
    case "ompi_rb_tree":
    case "ompi_value_array":
    case "ompi_list":
      ./$target
      breaksw
    case "help"    
    default     
      echo "correct use: "
      echo "    run_tests    (to run all class tests)"
      echo "or  run_tests with any combination of the following: "
      echo  "       <ompi_bimmap | ompi_hash_table | onpi_list | "
      echo "         ompi_pointer_array | ompi_rb_tree | ompi_value_array>"
      break
    endsw
  end

endif


