#!/bin/bash
#
# Copyright (c) 2004-2005 The Trustees of Indiana University.
#                         All rights reserved.
# Copyright (c) 2004-2005 The Trustees of the University of Tennessee.
#                         All rights reserved.
# $COPYRIGHT$
# 
# Additional copyrights may follow
# 
# $HEADER$
#
# Quick and dirty hack of an mpirun to be used only with the cofs
# "RTE" (if you can call it that).  Does not guarantee cleanup just
# yet (still trying to figure out how to make that one work..
#
# On the other hand, it will get us to MPI_INIT faster than just about
# any other idea I have...
#
# hboot is used to start procs on the remote side.  fun, fun


######################################################################
#
# Some basic defaults
#
######################################################################
ompi_procid=""
ompi_numprocs=""
ompi_jobid=""
ompi_commdir=""

######################################################################
#
# Do argument parsing
#
######################################################################
args_err=1

for i ; do
    case "${i}" in
        -test)
            exit 0
            ;;
        -cellid)
            shift
            ompi_cellid="${1}"
            shift
            ;;
        -jobid)
            shift
            ompi_jobid="${1}"
            shift
            ;;
        -procid)
            shift
            ompi_procid="${1}"
            shift
            ;;
        -numprocs)
            shift
            ompi_numprocs="${1}"
            shift
            ;;
        -commdir)
            shift
            ompi_commdir="${1}"
            shift
            ;;
        -x)
            shift
            name="${1}"
            shift
            val="${1}"
            shift
            export "${name}"="${val}"
            ;;
        -pwd)
            shift
            cd "${1}"
            shift
            ;;
        --)
            shift
            args_err=0
            ;;
    esac
done

if test "${args_err}" != "0" ; then
    echo "Argument parse error - did not find -- "
    exit 1
fi
if test -z "${1}" ; then
    echo "Did not find app to execute: " ${1}
    exit 2
fi

######################################################################
#
# Set the environment
#
######################################################################
export OMPI_MCA_pcmclient_env_cellid="${ompi_cellid}"
export OMPI_MCA_pcmclient_env_jobid="${ompi_jobid}"
export OMPI_MCA_pcmclient_env_procid="${ompi_procid}"
export OMPI_MCA_pcmclient_env_num_procs="${ompi_numprocs}"
export OMPI_MCA_pcmclient_env_vpid_start="0"
if test ! -z "${ompi_commdir}"; then
    export OMPI_MCA_oob_cofs_dir="${ompi_commdir}"
fi

######################################################################
#
# Spawn and run
#
######################################################################
exec $@
