#!/bin/bash
#
# $HEADER$
#
# Quick and dirty hack of an mpirun to be used only with the cofs
# "RTE" (if you can call it that).  Does not guarantee cleanup just
# yet (still trying to figure out how to make that one work..
#
# On the other hand, it will get us to MPI_INIT faster than just about
# any other idea I have...
#
# hboot is used to start procs on the remote side.  fun, fun


######################################################################
#
# Some basic defaults
#
######################################################################
ompi_myvpid=""
ompi_numprocs=""
ompi_jobhandle=""
ompi_commdir=""

######################################################################
#
# Do argument parsing
#
######################################################################
args_err=1

for i ; do
    case "${i}" in
        -test)
            exit 0
            ;;
        -myvpid)
            shift
            ompi_myvpid="${1}"
            shift
            ;;
        -numprocs)
            shift
            ompi_numprocs="${1}"
            shift
            ;;
        -jobhandle)
            shift
            ompi_jobhandle="${1}"
            shift
            ;;
        -commdir)
            shift
            ompi_commdir="${1}"
            shift
            ;;
        -x)
            shift
            name="${1}"
            shift
            val="${1}"
            shift
            export "${name}"="${val}"
            ;;
        -pwd)
            shift
            cd "${1}"
            shift
            ;;
        --)
            shift
            args_err=0
            ;;
    esac
done

if test "${args_err}" != "0" ; then
    echo "Argument parse error - did not find -- "
    exit 1
fi
if test -z "${1}" ; then
    echo "Did not find app to execute"
    exit 2
fi

######################################################################
#
# Set the environment
#
######################################################################
export MCA_common_ompi_cofs_my_vpid="${ompi_myvpid}"
export MCA_common_ompi_cofs_num_procs="${ompi_numprocs}"
export MCA_common_ompi_cofs_job_handle="${ompi_jobhandle}"
if test ! -z "${ompi_commdir}"; then
    export MCA_common_ompi_cofs_comm_dir="${ompi_commdir}"
fi

######################################################################
#
# Spawn and run
#
######################################################################
exec $@
