#! /bin/csh -f
#  Name
#  ====
#  run script for mpi tests

# Arguements
# ==========
# 
# test_list  =  no args or all runs all tests
#              or
#               llm runs ompi mpi llm tests
#               ns runs ompi mpi ns tests
#               oob runs ompi mpi oob tests 
#               pcm runs ompi mpi pcm tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  cd environment; ./run_tests all; cd ..;
else

  foreach target ($argv)
    switch ($target)
    case "all":
      cd ../environment; ./run_tests all; cd ..;
      breaksw
    case "environment":
      cd $target
      ./run_tests;
      cd ..;
      breaksw
    case "help":      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all  (to run all mpi tests)"
      echo "or  run_tests <llm | ns | oob | pcm>"
      breaksw
    default
      echo "There is no part of mpia tests called program <$target> to run"
      echo "correct use: "
      echo "    run_tests all   (to run all mpi tests)"
      echo "or  run_tests <environment>"
      break
    endsw
  end

endif


