#! /bin/csh -f
#  Name
#  ====
#  run script for mca oob tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               oob_test runs ompi mca oob_test
#               oob_test_self runs ompi mca oob_test_self test
#               oob_test_packed runs ompi mca oob_test_packed test

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

MPIRUN = mpirun
umask 007

if ("x$1" == "x") then
  mpirun -np 2 -- ./oob_test;
  mpirun -np 1 -- ./oob_test_self;
  mpirun -np 2 -- ./oob_test_packed;
else 
  foreach target ($argv)
    switch ($target)
    case "all":
      mpirun -np 2 -- ./oob_test;
      mpirun -np 1 -- ./oob_test_self;
      mpirun -np 2 -- ./oob_test_packed;
      breaksw
    case "oob_test_self":
      mpirun -np 1 -- ./oob_test_self;
      breaksw
    case "oob_test":
    case "oob_test_packed":
      mpirun -np 2 -- ./$target;
      breaksw
    case "help"
       echo "correct use: "
       echo "    run_tests help (this message)"
       echo "    run_tests    (to run all oob tests)"
       echo "or  run_tests <oob_test | oob_test_self | oob_test_packed>"
       break
       breaksw
    default
       echo "There is no test <$target> to run"
       echo "correct use: "
       echo "    run_tests    (to run all oob tests)"
       echo "or  run_tests <oob_test | oob_test_self | oob_test_packed>"
       break
    endsw
  end
endif


