.TH "Retrieve Objects" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Retrieve Objects \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "HWLOC_DECLSPEC \fBhwloc_obj_t\fP \fBhwloc_get_obj_by_depth\fP (\fBhwloc_topology_t\fP topology, unsigned depth, unsigned idx) __hwloc_attribute_pure"
.br
.RI "\fIReturns the topology object at index \fCindex\fP from depth \fCdepth\fP. \fP"
.ti -1c
.RI "static __inline \fBhwloc_obj_t\fP __hwloc_attribute_pure \fBhwloc_get_obj_by_type\fP (\fBhwloc_topology_t\fP topology, \fBhwloc_obj_type_t\fP type, unsigned idx)"
.br
.RI "\fIReturns the topology object at index \fCindex\fP with type \fCtype\fP. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "HWLOC_DECLSPEC \fBhwloc_obj_t\fP hwloc_get_obj_by_depth (\fBhwloc_topology_t\fP topology, unsigned depth, unsigned idx)"
.PP
Returns the topology object at index \fCindex\fP from depth \fCdepth\fP. 
.SS "static __inline \fBhwloc_obj_t\fP __hwloc_attribute_pure hwloc_get_obj_by_type (\fBhwloc_topology_t\fP topology, \fBhwloc_obj_type_t\fP type, unsigned idx)\fC [static]\fP"
.PP
Returns the topology object at index \fCindex\fP with type \fCtype\fP. If no object for that type exists, \fCNULL\fP is returned. If there are several levels with objects of that type, \fCNULL\fP is returned and ther caller may fallback to \fBhwloc_get_obj_by_depth()\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
