.TH "Helpers for manipulating Linux libnuma nodemask_t" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helpers for manipulating Linux libnuma nodemask_t \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "static __inline int \fBhwloc_cpuset_to_linux_libnuma_nodemask\fP (\fBhwloc_topology_t\fP topology, \fBhwloc_const_cpuset_t\fP cpuset, nodemask_t *nodemask)"
.br
.RI "\fIConvert hwloc CPU set \fCcpuset\fP into libnuma nodemask \fCnodemask\fP. \fP"
.ti -1c
.RI "static __inline int \fBhwloc_cpuset_from_linux_libnuma_nodemask\fP (\fBhwloc_topology_t\fP topology, \fBhwloc_cpuset_t\fP cpuset, const nodemask_t *nodemask)"
.br
.RI "\fIConvert libnuma nodemask \fCnodemask\fP into hwloc CPU set \fCcpuset\fP. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "static __inline int hwloc_cpuset_from_linux_libnuma_nodemask (\fBhwloc_topology_t\fP topology, \fBhwloc_cpuset_t\fP cpuset, const nodemask_t * nodemask)\fC [static]\fP"
.PP
Convert libnuma nodemask \fCnodemask\fP into hwloc CPU set \fCcpuset\fP. This function may be used before calling some old libnuma functions that use a nodemask_t as an output parameter. 
.SS "static __inline int hwloc_cpuset_to_linux_libnuma_nodemask (\fBhwloc_topology_t\fP topology, \fBhwloc_const_cpuset_t\fP cpuset, nodemask_t * nodemask)\fC [static]\fP"
.PP
Convert hwloc CPU set \fCcpuset\fP into libnuma nodemask \fCnodemask\fP. This function may be used before calling some old libnuma functions that use a nodemask_t as an input parameter. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
