.TH "Cache-specific Finding Helpers" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cache-specific Finding Helpers \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "static __inline \fBhwloc_obj_t\fP __hwloc_attribute_pure \fBhwloc_get_cache_covering_cpuset\fP (\fBhwloc_topology_t\fP topology, \fBhwloc_const_cpuset_t\fP set)"
.br
.RI "\fIGet the first cache covering a cpuset \fCset\fP. \fP"
.ti -1c
.RI "static __inline \fBhwloc_obj_t\fP __hwloc_attribute_pure \fBhwloc_get_shared_cache_covering_obj\fP (\fBhwloc_topology_t\fP topology __hwloc_attribute_unused, \fBhwloc_obj_t\fP obj)"
.br
.RI "\fIGet the first cache shared between an object and somebody else. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "static __inline \fBhwloc_obj_t\fP __hwloc_attribute_pure hwloc_get_cache_covering_cpuset (\fBhwloc_topology_t\fP topology, \fBhwloc_const_cpuset_t\fP set)\fC [static]\fP"
.PP
Get the first cache covering a cpuset \fCset\fP. \fBReturns:\fP
.RS 4
\fCNULL\fP if no cache matches 
.RE
.PP

.SS "static __inline \fBhwloc_obj_t\fP __hwloc_attribute_pure hwloc_get_shared_cache_covering_obj (\fBhwloc_topology_t\fP topology __hwloc_attribute_unused, \fBhwloc_obj_t\fP obj)\fC [static]\fP"
.PP
Get the first cache shared between an object and somebody else. \fBReturns:\fP
.RS 4
\fCNULL\fP if no cache matches 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
