.TH "hwloc_obj_attr_u::hwloc_group_attr_s" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_group_attr_s \- 
.PP
Group-specific Object Attributes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBdepth\fP"
.br
.RI "\fIDepth of group object. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Group-specific Object Attributes. 
.SH "Field Documentation"
.PP 
.SS "unsigned \fBhwloc_obj_attr_u::hwloc_group_attr_s::depth\fP"
.PP
Depth of group object. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
