.TH "hwloc_obj_attr_u::hwloc_machine_attr_s" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_machine_attr_s \- 
.PP
Machine-specific Object Attributes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBdmi_board_vendor\fP"
.br
.RI "\fIDMI board vendor name. \fP"
.ti -1c
.RI "char * \fBdmi_board_name\fP"
.br
.RI "\fIDMI board model name. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Machine-specific Object Attributes. 
.SH "Field Documentation"
.PP 
.SS "char* \fBhwloc_obj_attr_u::hwloc_machine_attr_s::dmi_board_name\fP"
.PP
DMI board model name. 
.SS "char* \fBhwloc_obj_attr_u::hwloc_machine_attr_s::dmi_board_vendor\fP"
.PP
DMI board vendor name. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
