.TH "Helpers for manipulating glibc sched affinity" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helpers for manipulating glibc sched affinity \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "static __inline int \fBhwloc_cpuset_to_glibc_sched_affinity\fP (\fBhwloc_topology_t\fP topology __hwloc_attribute_unused, \fBhwloc_const_cpuset_t\fP hwlocset, cpu_set_t *schedset, size_t schedsetsize)"
.br
.RI "\fIConvert hwloc CPU set \fCtoposet\fP into glibc sched affinity CPU set \fCschedset\fP. \fP"
.ti -1c
.RI "static __inline int \fBhwloc_cpuset_from_glibc_sched_affinity\fP (\fBhwloc_topology_t\fP topology __hwloc_attribute_unused, \fBhwloc_cpuset_t\fP hwlocset, const cpu_set_t *schedset, size_t schedsetsize)"
.br
.RI "\fIConvert glibc sched affinity CPU set \fCschedset\fP into hwloc CPU set. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "static __inline int hwloc_cpuset_from_glibc_sched_affinity (\fBhwloc_topology_t\fP topology __hwloc_attribute_unused, \fBhwloc_cpuset_t\fP hwlocset, const cpu_set_t * schedset, size_t schedsetsize)\fC [static]\fP"
.PP
Convert glibc sched affinity CPU set \fCschedset\fP into hwloc CPU set. This function may be used before calling sched_setaffinity or any other function that takes a cpu_set_t as input parameter.
.PP
\fCschedsetsize\fP should be sizeof(cpu_set_t) unless \fCschedset\fP was dynamically allocated with CPU_ALLOC 
.SS "static __inline int hwloc_cpuset_to_glibc_sched_affinity (\fBhwloc_topology_t\fP topology __hwloc_attribute_unused, \fBhwloc_const_cpuset_t\fP hwlocset, cpu_set_t * schedset, size_t schedsetsize)\fC [static]\fP"
.PP
Convert hwloc CPU set \fCtoposet\fP into glibc sched affinity CPU set \fCschedset\fP. This function may be used before calling sched_setaffinity or any other function that takes a cpu_set_t as input parameter.
.PP
\fCschedsetsize\fP should be sizeof(cpu_set_t) unless \fCschedset\fP was dynamically allocated with CPU_ALLOC 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
