.TH "hwloc_obj_attr_u" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u \- 
.PP
Object type-specific Attributes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_cache_attr_s\fP"
.br
.RI "\fICache-specific Object Attributes. \fP"
.ti -1c
.RI "struct \fBhwloc_group_attr_s\fP"
.br
.RI "\fIGroup-specific Object Attributes. \fP"
.ti -1c
.RI "struct \fBhwloc_machine_attr_s\fP"
.br
.RI "\fIMachine-specific Object Attributes. \fP"
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_cache_attr_s\fP \fBcache\fP"
.br
.RI "\fICache-specific Object Attributes. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_machine_attr_s\fP \fBmachine\fP"
.br
.RI "\fIMachine-specific Object Attributes. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_group_attr_s\fP \fBgroup\fP"
.br
.RI "\fIGroup-specific Object Attributes. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Object type-specific Attributes. 
.SH "Field Documentation"
.PP 
.SS "struct \fBhwloc_obj_attr_u::hwloc_cache_attr_s\fP  \fBhwloc_obj_attr_u::cache\fP"
.PP
Cache-specific Object Attributes. 
.SS "struct \fBhwloc_obj_attr_u::hwloc_group_attr_s\fP  \fBhwloc_obj_attr_u::group\fP"
.PP
Group-specific Object Attributes. 
.SS "struct \fBhwloc_obj_attr_u::hwloc_machine_attr_s\fP  \fBhwloc_obj_attr_u::machine\fP"
.PP
Machine-specific Object Attributes. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
