.TH "hwloc_topology_discovery_support" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_topology_discovery_support \- 
.PP
Flags describing actual discovery support for this topology.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBpu\fP"
.br
.RI "\fIDetecting the number of PU objects is supported. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Flags describing actual discovery support for this topology. 
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBhwloc_topology_discovery_support::pu\fP"
.PP
Detecting the number of PU objects is supported. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
