.TH "Topology Objects" 3 "17 Apr 2010" "Version 1.0rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Topology Objects \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_obj_memory_s\fP"
.br
.RI "\fIObject memory. \fP"
.ti -1c
.RI "struct \fBhwloc_obj\fP"
.br
.RI "\fIStructure of a topology object. \fP"
.ti -1c
.RI "union \fBhwloc_obj_attr_u\fP"
.br
.RI "\fIObject type-specific Attributes. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBhwloc_obj\fP * \fBhwloc_obj_t\fP"
.br
.RI "\fIConvenience typedef; a pointer to a struct \fBhwloc_obj\fP. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBhwloc_obj\fP* \fBhwloc_obj_t\fP"
.PP
Convenience typedef; a pointer to a struct \fBhwloc_obj\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
