#! /bin/csh -f
#  Name
#  ====
#  run script for rte tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               openmpi runs openmpi test

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  ./openmpi
else 
  foreach target ($argv)
    switch ($target)
    case "all":
      ./openmpi
      breaksw
    case "openmpi":
      ./$target
      breaksw
    case "help":
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests (to run all rte tests)"
      echo "or  run_tests <openmpi>"
      break
      breaksw
    default:
      echo "There is no program <$target> to run"
      echo "correct use: "
      echo "    run_tests (to run all rte tests)"
      echo "or  run_tests <openmpi>"
      break
    endsw
  end
endif


