#! /bin/csh -f
#  Name
#  ====
#  run for mca pcm base tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               sched_comm runs ompi pcm base sched_comm tests
#               build_env runs ompi pcm base build_env tests

# Usage
#
# =====
# To invoke this script, enter either
#     run 
# with no arguments to run all tests, or
#     run <test_name>

umask 007

if ("x$1" == "x") then
  ./sched_comm;
  ./build_env
else 
  foreach target ($argv)
    switch ($target)
    case "all"
      ./sched_comm;
      ./build_env
      breaksw
    case "sched_comm":
      ./sched_comm;
      breaksw
    case "build_env":
      ./build_env
      breaksw
    case "help":
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all   (to run all mca pcm base tests)"
      echo "or  run_tests < sched_comm | build_env >"
      break
      breaksw
    default
      echo "No test named <$target> available to run"
      echo "correct use: "
      echo "    run_tests all   (to run all mca pcm base tests)"
      echo "or  run_tests < sched_comm | build_env >"
      break
    endsw
  end
endif


