/*
 * Copyright © 2013 Inria.  All rights reserved.
 * See COPYING in top-level directory.
 */

#ifndef HWLOC_PORT_GL_NVCTRL_NVCTRL_H
#define HWLOC_PORT_GL_NVCTRL_NVCTRL_H

#define NV_CTRL_TARGET_TYPE_X_SCREEN 0
#define NV_CTRL_BINARY_DATA_GPUS_USED_BY_XSCREEN 4
#define NV_CTRL_TARGET_TYPE_GPU 1
#define NV_CTRL_PCI_DOMAIN 306
#define NV_CTRL_PCI_BUS 239
#define NV_CTRL_PCI_DEVICE 240
#define NV_CTRL_PCI_FUNCTION 241
#define NV_CTRL_STRING_PRODUCT_NAME 0

#endif /* HWLOC_PORT_GL_NVCTRL_NVCTRL_H */
