# Copyright (c) 2015-2016 Mellanox Technologies, Inc.
#                         All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$


headers += \
        dstore/pmix_dstore.h \
        dstore/pmix_esh.h

sources += \
        dstore/pmix_dstore.c \
        dstore/pmix_esh.c
