#! /bin/csh -f
#  Name
#  ====
#  run script for include tests

# Arguements
# ==========
# 
# test_list  =  no args or "all" runs all tests
#              or
#               atomic runs atomic tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  ./atomic
else 
  foreach target ($argv)
    switch ($target)
    case "all":
      ./atomic
      breaksw
    case "atomic"
      ./$target
      breaksw
    case "help"
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all (to run all include tests)"
      echo "or  run_tests <atomic>"
      break
    default
      echo "There is no program <$target> to run"
      echo "correct use: "
      echo "    run_tests help (this message)"
      echo "    run_tests all (to run all include tests)"
      echo "or  run_tests <atomic>"
      break
    endsw
  end

endif
