#! /bin/csh -f
#  Name
#  ====
#  run script for include tests

# Arguements
# ==========
# 
# test_list  =  no args runs all tests
#              or
#               atomic runs atomic tests

# Usage
#
# =====
# To invoke this script, enter either
#     run_tests 
# with no arguments to run all tests, or
#     run_tests <test_name>

umask 007

if ("x$1" == "x") then
  ./atomic
else if ("$1" == "atomic") then
  ./atomic
else
  echo "correct use: "
  echo "    run_tests (to run all class tests)"
  echo "or  run_tests <atomic>"
  exit -1
endif


