name: ompio

on: [pull_request]

permissions:
  contents: read

jobs:
  ompio-testsuite:
    runs-on: ubuntu-24.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends cmake
    - uses: actions/checkout@v6
      with:
            submodules: recursive
    - name: Build Open MPI
      run: |
        export AUTOMAKE_JOBS=$(nproc)
        ./autogen.pl
        ./configure --prefix=/opt/openmpi --with-pmix=internal --with-prrte=internal --with-hwloc=internal --with-libevent=internal --disable-mpi-fortran --disable-oshmem
        make -j 8 && make install
    - name: Install ompio testsuite
      run: |
         git clone --no-checkout --filter=blob:none https://github.com/edgargabriel/ompi-tests-public.git
         cd ompi-tests-public
         git sparse-checkout set --cone ompio-filetests
         git checkout master
         cd ompio-filetests
         export PATH=/opt/openmpi/bin:${PATH}
         export LD_LIBRARY_PATH=/opt/openmpi/lib:${LD_LIBRARY_PATH}
         echo ${PATH}
         echo ${LD_LIBRARY_PATH}
         cmake -S . -B build -DMPI_HOME=/opt/openmpi
         cmake --build build
    - name: Run testsuite (ompio)
      run: |
         export PATH=/opt/openmpi/bin:${PATH}
         export LD_LIBRARY_PATH=/opt/openmpi/lib:${LD_LIBRARY_PATH}
         mpirun --map-by core:oversubscribe --mca io ompio -np 6 ./build/filetests
